set script_dir [file dirname [file normalize [info script]]]
set root_dir [file normalize [file join $script_dir ..]]
set build_dir [file join $root_dir build]
set report_dir [file join $root_dir reports]
set part_name "xcu250-figd2104-2L-e"
set clock_ns 3.333
set version "attention_qkv_v6_7_rtl_synthesis_2026_07_13"

file mkdir $build_dir
file mkdir $report_dir

proc show_failure_logs {project_dir} {
    set db [file join $project_dir solution1 .autopilot db]
    foreach pattern [list "*clang*.err.log" "*.opt.err.log" "*.llvm-link.err.log"] {
        foreach path [glob -nocomplain [file join $db $pattern]] {
            if {[file size $path] > 0} {
                puts stderr "---- $path ----"
                set fh [open $path r]
                puts stderr [read $fh]
                close $fh
            }
        }
    }
    set flow [file join $db autopilot.flow.log]
    if {[file exists $flow] && [file size $flow] > 0} {
        set fh [open $flow r]
        set lines [split [read $fh] "\n"]
        close $fh
        puts stderr "---- autopilot.flow.log tail ----"
        foreach line [lrange $lines end-79 end] {
            puts stderr $line
        }
    }
}

proc copy_detailed_reports {project_dir top report_name} {
    global report_dir
    set syn_report_dir [file join $project_dir solution1 syn report]

    # Vitis HLS 2022.1 writes the full hierarchy/loop/II/latency/resource table
    # shown in the GUI to csynth.rpt. Prefer it over the per-function report.
    set primary [file join $syn_report_dir csynth.rpt]
    if {![file exists $primary] || [file size $primary] == 0} {
        set primary [file join $syn_report_dir "${top}_csynth.rpt"]
    }
    if {![file exists $primary] || [file size $primary] == 0} {
        error "full csynth report is missing from $syn_report_dir"
    }

    set exported [file join $report_dir $report_name]
    file copy -force $primary $exported

    # Keep every module/loop report and machine-readable XML generated by HLS.
    set detail_dir [file join $report_dir details $top]
    file delete -force $detail_dir
    file mkdir $detail_dir
    foreach path [glob -nocomplain [file join $syn_report_dir *]] {
        if {[file isfile $path] && [file size $path] > 0} {
            file copy -force $path $detail_dir
        }
    }

    puts "Detailed summary: $exported ([file size $exported] bytes)"
    puts "All module reports: $detail_dir"
}

proc copy_rtl_synthesis_reports {project_dir top} {
    global report_dir
    set impl_report_dir [file join $project_dir solution1 impl report]
    if {![file isdirectory $impl_report_dir]} {
        error "RTL synthesis report directory is missing: $impl_report_dir"
    }

    set exported [file join $report_dir rtl_syn $top]
    file delete -force $exported
    file mkdir [file dirname $exported]
    file copy -force $impl_report_dir $exported
    puts "RTL synthesis reports: $exported"
}

proc synth_kernel {top source report_name} {
    global root_dir build_dir report_dir part_name clock_ns version
    set source_path [file join $root_dir kernels $source]
    set project_name "proj_${top}"
    set project_dir [file join $build_dir $project_name]

    puts "============================================================"
    puts "Script version: $version"
    puts "Kernel: $top"
    puts "Source: $source_path"
    puts "============================================================"

    set old_dir [pwd]
    set ok 1
    if {[catch {
        cd $build_dir
        open_project -reset $project_name
        add_files -cflags "-std=c++14 -I[file join $root_dir include]" $source_path
        set_top $top
        open_solution -reset solution1 -flow_target vivado
        set_part $part_name
        create_clock -period $clock_ns -name default
        csynth_design

        copy_detailed_reports $project_dir $top $report_name
        if {$top eq "bert_qkv_kernel"} {
            # Logic synthesis only: this does not run placement or routing.
            export_design -flow syn -rtl verilog
            copy_rtl_synthesis_reports $project_dir $top
        }
    } message]} {
        puts stderr "ERROR: $top: $message"
        show_failure_logs $project_dir
        set ok 0
    }
    catch {close_project}
    cd $old_dir
    return $ok
}

array set source_for {
    bert_qkv_kernel bert_qkv_kernel.cpp
    bert_attn_core_kernel bert_attn_core_kernel.cpp
    bert_attn_out_norm_kernel bert_attn_out_norm_kernel.cpp
}
array set report_for {
    bert_qkv_kernel csynth_qkv.rpt
    bert_attn_core_kernel csynth_attn_core.rpt
    bert_attn_out_norm_kernel csynth_attn_out_norm.rpt
}

set all_kernels [list bert_qkv_kernel bert_attn_core_kernel bert_attn_out_norm_kernel]
set selected {}
foreach arg $argv {
    if {[info exists source_for($arg)]} {
        lappend selected $arg
    }
}
if {[llength $selected] == 0} {
    set selected $all_kernels
}

set failed {}
foreach top $selected {
    if {[synth_kernel $top $source_for($top) $report_for($top)]} {
        puts "PASS: $top"
    } else {
        puts "FAIL: $top"
        lappend failed $top
    }
}

puts "============================================================"
if {[llength $failed] == 0} {
    puts "ALL SELECTED ATTENTION KERNELS PASSED"
    exit 0
}
puts stderr "FAILED: [join $failed {, }]"
exit 1
