-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bert_attn_out_norm_residual_kernel_load_norm_parameters is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_norm_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_norm_AWREADY : IN STD_LOGIC;
    m_axi_gmem_norm_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_norm_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_norm_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_norm_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_norm_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_norm_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_norm_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_norm_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_norm_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_norm_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_norm_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_norm_WVALID : OUT STD_LOGIC;
    m_axi_gmem_norm_WREADY : IN STD_LOGIC;
    m_axi_gmem_norm_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_norm_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_norm_WLAST : OUT STD_LOGIC;
    m_axi_gmem_norm_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_norm_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_norm_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_norm_ARREADY : IN STD_LOGIC;
    m_axi_gmem_norm_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_norm_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_norm_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_norm_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_norm_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_norm_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_norm_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_norm_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_norm_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_norm_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_norm_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_norm_RVALID : IN STD_LOGIC;
    m_axi_gmem_norm_RREADY : OUT STD_LOGIC;
    m_axi_gmem_norm_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_norm_RLAST : IN STD_LOGIC;
    m_axi_gmem_norm_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_norm_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_norm_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_norm_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_norm_BVALID : IN STD_LOGIC;
    m_axi_gmem_norm_BREADY : OUT STD_LOGIC;
    m_axi_gmem_norm_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_norm_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_norm_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    gamma : IN STD_LOGIC_VECTOR (63 downto 0);
    beta : IN STD_LOGIC_VECTOR (63 downto 0);
    gamma_cache_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    gamma_cache_ce1 : OUT STD_LOGIC;
    gamma_cache_we1 : OUT STD_LOGIC;
    gamma_cache_d1 : OUT STD_LOGIC_VECTOR (511 downto 0);
    beta_cache_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    beta_cache_ce1 : OUT STD_LOGIC;
    beta_cache_we1 : OUT STD_LOGIC;
    beta_cache_d1 : OUT STD_LOGIC_VECTOR (511 downto 0) );
end;


architecture behav of bert_attn_out_norm_residual_kernel_load_norm_parameters is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv6_30 : STD_LOGIC_VECTOR (5 downto 0) := "110000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal icmp_ln194_reg_247 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_io : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_state8_pp0_stage1_iter3 : BOOLEAN;
    signal ap_block_state10_pp0_stage1_iter4 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_norm_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal gmem_norm_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_4_reg_242 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_4_reg_242_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal p_4_reg_242_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal p_4_reg_242_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal p_4_reg_242_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln194_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln194_reg_247_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln194_reg_247_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln194_reg_247_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln713_fu_194_p2 : STD_LOGIC_VECTOR (58 downto 0);
    signal add_ln713_reg_251 : STD_LOGIC_VECTOR (58 downto 0);
    signal add_ln713_1_fu_200_p2 : STD_LOGIC_VECTOR (58 downto 0);
    signal add_ln713_1_reg_256 : STD_LOGIC_VECTOR (58 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal t_reg_273 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln194_fu_231_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln194_reg_278 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_1_reg_283 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal sext_ln713_fu_211_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln713_1_fu_221_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_fu_68 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln194_fu_184_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_p_4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln_fu_142_p4 : STD_LOGIC_VECTOR (57 downto 0);
    signal trunc_ln194_1_fu_156_p4 : STD_LOGIC_VECTOR (57 downto 0);
    signal zext_ln194_1_fu_190_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal sext_ln194_fu_152_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal sext_ln194_1_fu_166_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter4_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to5 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bert_attn_out_norm_residual_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component bert_attn_out_norm_residual_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    p_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln194_fu_178_p2 = ap_const_lv1_0))) then 
                    p_fu_68 <= add_ln194_fu_184_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    p_fu_68 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln194_fu_178_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln713_1_reg_256 <= add_ln713_1_fu_200_p2;
                add_ln713_reg_251 <= add_ln713_fu_194_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln194_reg_247 <= icmp_ln194_fu_178_p2;
                icmp_ln194_reg_247_pp0_iter1_reg <= icmp_ln194_reg_247;
                icmp_ln194_reg_247_pp0_iter2_reg <= icmp_ln194_reg_247_pp0_iter1_reg;
                icmp_ln194_reg_247_pp0_iter3_reg <= icmp_ln194_reg_247_pp0_iter2_reg;
                p_4_reg_242 <= ap_sig_allocacmp_p_4;
                p_4_reg_242_pp0_iter1_reg <= p_4_reg_242;
                p_4_reg_242_pp0_iter2_reg <= p_4_reg_242_pp0_iter1_reg;
                p_4_reg_242_pp0_iter3_reg <= p_4_reg_242_pp0_iter2_reg;
                p_4_reg_242_pp0_iter4_reg <= p_4_reg_242_pp0_iter3_reg;
                t_reg_273 <= m_axi_gmem_norm_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                t_1_reg_283 <= m_axi_gmem_norm_RDATA;
                    zext_ln194_reg_278(5 downto 0) <= zext_ln194_fu_231_p1(5 downto 0);
            end if;
        end if;
    end process;
    zext_ln194_reg_278(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter4_stage0, ap_idle_pp0_0to3, ap_idle_pp0_1to5, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to5 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln194_fu_184_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_p_4) + unsigned(ap_const_lv6_1));
    add_ln713_1_fu_200_p2 <= std_logic_vector(unsigned(zext_ln194_1_fu_190_p1) + unsigned(sext_ln194_1_fu_166_p1));
    add_ln713_fu_194_p2 <= std_logic_vector(unsigned(zext_ln194_1_fu_190_p1) + unsigned(sext_ln194_fu_152_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, m_axi_gmem_norm_ARREADY, m_axi_gmem_norm_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_gmem_norm_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((m_axi_gmem_norm_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, m_axi_gmem_norm_ARREADY, m_axi_gmem_norm_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_gmem_norm_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((m_axi_gmem_norm_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter4, m_axi_gmem_norm_RVALID, ap_block_state2_io)
    begin
                ap_block_pp0_stage1_11001 <= (((m_axi_gmem_norm_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io)));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter4, m_axi_gmem_norm_RVALID, ap_block_state2_io)
    begin
                ap_block_pp0_stage1_subdone <= (((m_axi_gmem_norm_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io)));
    end process;


    ap_block_state10_pp0_stage1_iter4_assign_proc : process(m_axi_gmem_norm_RVALID)
    begin
                ap_block_state10_pp0_stage1_iter4 <= (m_axi_gmem_norm_RVALID = ap_const_logic_0);
    end process;

        ap_block_state11_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_io_assign_proc : process(m_axi_gmem_norm_ARREADY, icmp_ln194_reg_247)
    begin
                ap_block_state2_io <= ((m_axi_gmem_norm_ARREADY = ap_const_logic_0) and (icmp_ln194_reg_247 = ap_const_lv1_0));
    end process;

        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage1_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_pp0_stage0_iter4_assign_proc : process(m_axi_gmem_norm_RVALID)
    begin
                ap_block_state9_pp0_stage0_iter4 <= (m_axi_gmem_norm_RVALID = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln194_reg_247, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (icmp_ln194_reg_247 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter4_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, icmp_ln194_reg_247_pp0_iter3_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln194_reg_247_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to5 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to5 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_p_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, p_fu_68, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_p_4 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_p_4 <= p_fu_68;
        end if; 
    end process;

    beta_cache_address1 <= zext_ln194_reg_278(6 - 1 downto 0);

    beta_cache_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            beta_cache_ce1 <= ap_const_logic_1;
        else 
            beta_cache_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    beta_cache_d1 <= t_1_reg_283;

    beta_cache_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            beta_cache_we1 <= ap_const_logic_1;
        else 
            beta_cache_we1 <= ap_const_logic_0;
        end if; 
    end process;

    gamma_cache_address1 <= zext_ln194_fu_231_p1(6 - 1 downto 0);

    gamma_cache_ce1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
            gamma_cache_ce1 <= ap_const_logic_1;
        else 
            gamma_cache_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    gamma_cache_d1 <= t_reg_273;

    gamma_cache_we1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
            gamma_cache_we1 <= ap_const_logic_1;
        else 
            gamma_cache_we1 <= ap_const_logic_0;
        end if; 
    end process;


    gmem_norm_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, m_axi_gmem_norm_ARREADY, icmp_ln194_reg_247, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (icmp_ln194_reg_247 = ap_const_lv1_0)))) then 
            gmem_norm_blk_n_AR <= m_axi_gmem_norm_ARREADY;
        else 
            gmem_norm_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_norm_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, m_axi_gmem_norm_RVALID, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            gmem_norm_blk_n_R <= m_axi_gmem_norm_RVALID;
        else 
            gmem_norm_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln194_fu_178_p2 <= "1" when (ap_sig_allocacmp_p_4 = ap_const_lv6_30) else "0";

    m_axi_gmem_norm_ARADDR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln194_reg_247, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, sext_ln713_fu_211_p1, sext_ln713_1_fu_221_p1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem_norm_ARADDR <= sext_ln713_1_fu_221_p1;
        elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln194_reg_247 = ap_const_lv1_0))) then 
            m_axi_gmem_norm_ARADDR <= sext_ln713_fu_211_p1;
        else 
            m_axi_gmem_norm_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_gmem_norm_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_norm_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_norm_ARID <= ap_const_lv1_0;
    m_axi_gmem_norm_ARLEN <= ap_const_lv32_1;
    m_axi_gmem_norm_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_norm_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_norm_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_norm_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_norm_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_norm_ARUSER <= ap_const_lv1_0;

    m_axi_gmem_norm_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln194_reg_247, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln194_reg_247 = ap_const_lv1_0)))) then 
            m_axi_gmem_norm_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_norm_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_norm_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_norm_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_norm_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_norm_AWID <= ap_const_lv1_0;
    m_axi_gmem_norm_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_norm_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_norm_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_norm_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_norm_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_norm_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_norm_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_norm_AWVALID <= ap_const_logic_0;
    m_axi_gmem_norm_BREADY <= ap_const_logic_0;

    m_axi_gmem_norm_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            m_axi_gmem_norm_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_norm_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_norm_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem_norm_WID <= ap_const_lv1_0;
    m_axi_gmem_norm_WLAST <= ap_const_logic_0;
    m_axi_gmem_norm_WSTRB <= ap_const_lv64_0;
    m_axi_gmem_norm_WUSER <= ap_const_lv1_0;
    m_axi_gmem_norm_WVALID <= ap_const_logic_0;
        sext_ln194_1_fu_166_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln194_1_fu_156_p4),59));

        sext_ln194_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_142_p4),59));

        sext_ln713_1_fu_221_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln713_1_reg_256),64));

        sext_ln713_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln713_reg_251),64));

    trunc_ln194_1_fu_156_p4 <= beta(63 downto 6);
    trunc_ln_fu_142_p4 <= gamma(63 downto 6);
    zext_ln194_1_fu_190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_p_4),59));
    zext_ln194_fu_231_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_4_reg_242_pp0_iter4_reg),64));
end behav;
