-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bert_attn_out_norm_residual_kernel_load_residual is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_hidden_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_hidden_AWREADY : IN STD_LOGIC;
    m_axi_gmem_hidden_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_hidden_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_hidden_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_hidden_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_hidden_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_hidden_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_hidden_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_hidden_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_hidden_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_hidden_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_WVALID : OUT STD_LOGIC;
    m_axi_gmem_hidden_WREADY : IN STD_LOGIC;
    m_axi_gmem_hidden_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_hidden_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_hidden_WLAST : OUT STD_LOGIC;
    m_axi_gmem_hidden_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_hidden_ARREADY : IN STD_LOGIC;
    m_axi_gmem_hidden_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_hidden_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_hidden_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_hidden_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_hidden_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_hidden_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_hidden_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_hidden_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_hidden_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_hidden_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_RVALID : IN STD_LOGIC;
    m_axi_gmem_hidden_RREADY : OUT STD_LOGIC;
    m_axi_gmem_hidden_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_hidden_RLAST : IN STD_LOGIC;
    m_axi_gmem_hidden_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_hidden_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_hidden_BVALID : IN STD_LOGIC;
    m_axi_gmem_hidden_BREADY : OUT STD_LOGIC;
    m_axi_gmem_hidden_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_hidden_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    residual_in : IN STD_LOGIC_VECTOR (63 downto 0);
    residual_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    residual_ce1 : OUT STD_LOGIC;
    residual_we1 : OUT STD_LOGIC;
    residual_d1 : OUT STD_LOGIC_VECTOR (511 downto 0) );
end;


architecture behav of bert_attn_out_norm_residual_kernel_load_residual is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1800 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001100000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal gmem_hidden_blk_n_AR : STD_LOGIC;
    signal trunc_ln_fu_66_p4 : STD_LOGIC_VECTOR (57 downto 0);
    signal trunc_ln_reg_87 : STD_LOGIC_VECTOR (57 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_start : STD_LOGIC;
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_done : STD_LOGIC;
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_idle : STD_LOGIC;
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_ready : STD_LOGIC;
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWVALID : STD_LOGIC;
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_WVALID : STD_LOGIC;
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_WLAST : STD_LOGIC;
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARVALID : STD_LOGIC;
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_RREADY : STD_LOGIC;
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_BREADY : STD_LOGIC;
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_residual_address1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_residual_ce1 : STD_LOGIC;
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_residual_we1 : STD_LOGIC;
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_residual_d1 : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal sext_ln11_fu_76_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bert_attn_out_norm_residual_kernel_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_hidden_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_hidden_AWREADY : IN STD_LOGIC;
        m_axi_gmem_hidden_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_hidden_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_hidden_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_hidden_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_hidden_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_hidden_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_hidden_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_hidden_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_hidden_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_hidden_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_hidden_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_hidden_WVALID : OUT STD_LOGIC;
        m_axi_gmem_hidden_WREADY : IN STD_LOGIC;
        m_axi_gmem_hidden_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem_hidden_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_hidden_WLAST : OUT STD_LOGIC;
        m_axi_gmem_hidden_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_hidden_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_hidden_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_hidden_ARREADY : IN STD_LOGIC;
        m_axi_gmem_hidden_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_hidden_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_hidden_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_hidden_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_hidden_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_hidden_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_hidden_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_hidden_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_hidden_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_hidden_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_hidden_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_hidden_RVALID : IN STD_LOGIC;
        m_axi_gmem_hidden_RREADY : OUT STD_LOGIC;
        m_axi_gmem_hidden_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem_hidden_RLAST : IN STD_LOGIC;
        m_axi_gmem_hidden_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_hidden_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_hidden_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_hidden_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_hidden_BVALID : IN STD_LOGIC;
        m_axi_gmem_hidden_BREADY : OUT STD_LOGIC;
        m_axi_gmem_hidden_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_hidden_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_hidden_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        sext_ln11 : IN STD_LOGIC_VECTOR (57 downto 0);
        residual_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
        residual_ce1 : OUT STD_LOGIC;
        residual_we1 : OUT STD_LOGIC;
        residual_d1 : OUT STD_LOGIC_VECTOR (511 downto 0) );
    end component;



begin
    grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57 : component bert_attn_out_norm_residual_kernel_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_start,
        ap_done => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_done,
        ap_idle => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_idle,
        ap_ready => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_ready,
        m_axi_gmem_hidden_AWVALID => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWVALID,
        m_axi_gmem_hidden_AWREADY => ap_const_logic_0,
        m_axi_gmem_hidden_AWADDR => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWADDR,
        m_axi_gmem_hidden_AWID => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWID,
        m_axi_gmem_hidden_AWLEN => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWLEN,
        m_axi_gmem_hidden_AWSIZE => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWSIZE,
        m_axi_gmem_hidden_AWBURST => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWBURST,
        m_axi_gmem_hidden_AWLOCK => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWLOCK,
        m_axi_gmem_hidden_AWCACHE => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWCACHE,
        m_axi_gmem_hidden_AWPROT => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWPROT,
        m_axi_gmem_hidden_AWQOS => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWQOS,
        m_axi_gmem_hidden_AWREGION => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWREGION,
        m_axi_gmem_hidden_AWUSER => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_AWUSER,
        m_axi_gmem_hidden_WVALID => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_WVALID,
        m_axi_gmem_hidden_WREADY => ap_const_logic_0,
        m_axi_gmem_hidden_WDATA => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_WDATA,
        m_axi_gmem_hidden_WSTRB => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_WSTRB,
        m_axi_gmem_hidden_WLAST => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_WLAST,
        m_axi_gmem_hidden_WID => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_WID,
        m_axi_gmem_hidden_WUSER => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_WUSER,
        m_axi_gmem_hidden_ARVALID => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARVALID,
        m_axi_gmem_hidden_ARREADY => m_axi_gmem_hidden_ARREADY,
        m_axi_gmem_hidden_ARADDR => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARADDR,
        m_axi_gmem_hidden_ARID => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARID,
        m_axi_gmem_hidden_ARLEN => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARLEN,
        m_axi_gmem_hidden_ARSIZE => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARSIZE,
        m_axi_gmem_hidden_ARBURST => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARBURST,
        m_axi_gmem_hidden_ARLOCK => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARLOCK,
        m_axi_gmem_hidden_ARCACHE => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARCACHE,
        m_axi_gmem_hidden_ARPROT => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARPROT,
        m_axi_gmem_hidden_ARQOS => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARQOS,
        m_axi_gmem_hidden_ARREGION => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARREGION,
        m_axi_gmem_hidden_ARUSER => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARUSER,
        m_axi_gmem_hidden_RVALID => m_axi_gmem_hidden_RVALID,
        m_axi_gmem_hidden_RREADY => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_RREADY,
        m_axi_gmem_hidden_RDATA => m_axi_gmem_hidden_RDATA,
        m_axi_gmem_hidden_RLAST => m_axi_gmem_hidden_RLAST,
        m_axi_gmem_hidden_RID => m_axi_gmem_hidden_RID,
        m_axi_gmem_hidden_RFIFONUM => m_axi_gmem_hidden_RFIFONUM,
        m_axi_gmem_hidden_RUSER => m_axi_gmem_hidden_RUSER,
        m_axi_gmem_hidden_RRESP => m_axi_gmem_hidden_RRESP,
        m_axi_gmem_hidden_BVALID => ap_const_logic_0,
        m_axi_gmem_hidden_BREADY => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_BREADY,
        m_axi_gmem_hidden_BRESP => ap_const_lv2_0,
        m_axi_gmem_hidden_BID => ap_const_lv1_0,
        m_axi_gmem_hidden_BUSER => ap_const_lv1_0,
        sext_ln11 => trunc_ln_reg_87,
        residual_address1 => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_residual_address1,
        residual_ce1 => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_residual_ce1,
        residual_we1 => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_residual_we1,
        residual_d1 => grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_residual_d1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_ready = ap_const_logic_1)) then 
                    grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                trunc_ln_reg_87 <= residual_in(63 downto 6);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, m_axi_gmem_hidden_ARREADY, grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_done, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((m_axi_gmem_hidden_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, m_axi_gmem_hidden_ARREADY)
    begin
        if (((m_axi_gmem_hidden_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_done)
    begin
        if ((grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_done, ap_CS_fsm_state9)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_done = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_done, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    gmem_hidden_blk_n_AR_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_gmem_hidden_ARREADY)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            gmem_hidden_blk_n_AR <= m_axi_gmem_hidden_ARREADY;
        else 
            gmem_hidden_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;

    grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_start <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_ap_start_reg;

    m_axi_gmem_hidden_ARADDR_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_gmem_hidden_ARREADY, grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARADDR, ap_CS_fsm_state8, ap_CS_fsm_state9, sext_ln11_fu_76_p1)
    begin
        if ((not(((m_axi_gmem_hidden_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_gmem_hidden_ARADDR <= sext_ln11_fu_76_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_ARADDR <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARADDR;
        else 
            m_axi_gmem_hidden_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem_hidden_ARBURST_assign_proc : process(grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARBURST, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_ARBURST <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARBURST;
        else 
            m_axi_gmem_hidden_ARBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem_hidden_ARCACHE_assign_proc : process(grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARCACHE, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_ARCACHE <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARCACHE;
        else 
            m_axi_gmem_hidden_ARCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem_hidden_ARID_assign_proc : process(grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARID, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_ARID <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARID;
        else 
            m_axi_gmem_hidden_ARID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem_hidden_ARLEN_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_gmem_hidden_ARREADY, grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARLEN, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((not(((m_axi_gmem_hidden_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_gmem_hidden_ARLEN <= ap_const_lv32_1800;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_ARLEN <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARLEN;
        else 
            m_axi_gmem_hidden_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem_hidden_ARLOCK_assign_proc : process(grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARLOCK, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_ARLOCK <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARLOCK;
        else 
            m_axi_gmem_hidden_ARLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem_hidden_ARPROT_assign_proc : process(grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARPROT, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_ARPROT <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARPROT;
        else 
            m_axi_gmem_hidden_ARPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem_hidden_ARQOS_assign_proc : process(grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARQOS, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_ARQOS <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARQOS;
        else 
            m_axi_gmem_hidden_ARQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem_hidden_ARREGION_assign_proc : process(grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARREGION, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_ARREGION <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARREGION;
        else 
            m_axi_gmem_hidden_ARREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem_hidden_ARSIZE_assign_proc : process(grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARSIZE, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_ARSIZE <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARSIZE;
        else 
            m_axi_gmem_hidden_ARSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem_hidden_ARUSER_assign_proc : process(grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARUSER, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_ARUSER <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARUSER;
        else 
            m_axi_gmem_hidden_ARUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem_hidden_ARVALID_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_gmem_hidden_ARREADY, grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARVALID, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((not(((m_axi_gmem_hidden_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_gmem_hidden_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_ARVALID <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_ARVALID;
        else 
            m_axi_gmem_hidden_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_hidden_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_hidden_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_hidden_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_hidden_AWID <= ap_const_lv1_0;
    m_axi_gmem_hidden_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_hidden_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_hidden_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_hidden_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_hidden_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_hidden_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_hidden_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_hidden_AWVALID <= ap_const_logic_0;
    m_axi_gmem_hidden_BREADY <= ap_const_logic_0;

    m_axi_gmem_hidden_RREADY_assign_proc : process(grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_RREADY, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_gmem_hidden_RREADY <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_m_axi_gmem_hidden_RREADY;
        else 
            m_axi_gmem_hidden_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_hidden_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem_hidden_WID <= ap_const_lv1_0;
    m_axi_gmem_hidden_WLAST <= ap_const_logic_0;
    m_axi_gmem_hidden_WSTRB <= ap_const_lv64_0;
    m_axi_gmem_hidden_WUSER <= ap_const_lv1_0;
    m_axi_gmem_hidden_WVALID <= ap_const_logic_0;
    residual_address1 <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_residual_address1;
    residual_ce1 <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_residual_ce1;
    residual_d1 <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_residual_d1;
    residual_we1 <= grp_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK_fu_57_residual_we1;
        sext_ln11_fu_76_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_66_p4),64));

    trunc_ln_fu_66_p4 <= residual_in(63 downto 6);
end behav;
