-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bert_attn_out_norm_residual_kernel_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_hidden_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_hidden_AWREADY : IN STD_LOGIC;
    m_axi_gmem_hidden_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_hidden_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_hidden_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_hidden_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_hidden_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_hidden_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_hidden_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_hidden_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_hidden_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_hidden_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_WVALID : OUT STD_LOGIC;
    m_axi_gmem_hidden_WREADY : IN STD_LOGIC;
    m_axi_gmem_hidden_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_hidden_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_hidden_WLAST : OUT STD_LOGIC;
    m_axi_gmem_hidden_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_hidden_ARREADY : IN STD_LOGIC;
    m_axi_gmem_hidden_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_hidden_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_hidden_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_hidden_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_hidden_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_hidden_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_hidden_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_hidden_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_hidden_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_hidden_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_RVALID : IN STD_LOGIC;
    m_axi_gmem_hidden_RREADY : OUT STD_LOGIC;
    m_axi_gmem_hidden_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_hidden_RLAST : IN STD_LOGIC;
    m_axi_gmem_hidden_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_hidden_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_hidden_BVALID : IN STD_LOGIC;
    m_axi_gmem_hidden_BREADY : OUT STD_LOGIC;
    m_axi_gmem_hidden_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_hidden_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_hidden_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln11 : IN STD_LOGIC_VECTOR (57 downto 0);
    residual_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    residual_ce1 : OUT STD_LOGIC;
    residual_we1 : OUT STD_LOGIC;
    residual_d1 : OUT STD_LOGIC_VECTOR (511 downto 0) );
end;


architecture behav of bert_attn_out_norm_residual_kernel_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1800 : STD_LOGIC_VECTOR (12 downto 0) := "1100000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv6_30 : STD_LOGIC_VECTOR (5 downto 0) := "110000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln11_reg_279 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln11_fu_136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_hidden_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln21_fu_227_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln21_reg_283 : STD_LOGIC_VECTOR (12 downto 0);
    signal t_reg_288 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal zext_ln21_2_fu_249_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_fu_74 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln13_fu_233_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal s_fu_78 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln11_1_fu_185_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten_fu_82 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln11_1_fu_142_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln13_fu_171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln11_fu_165_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln21_fu_193_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_s_fu_205_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_fu_197_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln21_fu_213_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln11_fu_177_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln21_fu_217_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln21_1_fu_223_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bert_attn_out_norm_residual_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component bert_attn_out_norm_residual_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln11_fu_136_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_82 <= add_ln11_1_fu_142_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_82 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    p_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    p_fu_74 <= ap_const_lv6_0;
                elsif (((icmp_ln11_reg_279 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    p_fu_74 <= add_ln13_fu_233_p2;
                end if;
            end if; 
        end if;
    end process;

    s_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    s_fu_78 <= ap_const_lv8_0;
                elsif (((icmp_ln11_reg_279 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    s_fu_78 <= select_ln11_1_fu_185_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln11_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln21_reg_283 <= add_ln21_fu_227_p2;
                t_reg_288 <= m_axi_gmem_hidden_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln11_reg_279 <= icmp_ln11_fu_136_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln11_1_fu_142_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv13_1));
    add_ln11_fu_165_p2 <= std_logic_vector(unsigned(s_fu_78) + unsigned(ap_const_lv8_1));
    add_ln13_fu_233_p2 <= std_logic_vector(unsigned(select_ln11_fu_177_p3) + unsigned(ap_const_lv6_1));
    add_ln21_fu_227_p2 <= std_logic_vector(unsigned(sub_ln21_fu_217_p2) + unsigned(zext_ln21_1_fu_223_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem_hidden_RVALID, icmp_ln11_reg_279)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln11_reg_279 = ap_const_lv1_0) and (m_axi_gmem_hidden_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem_hidden_RVALID, icmp_ln11_reg_279)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln11_reg_279 = ap_const_lv1_0) and (m_axi_gmem_hidden_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_gmem_hidden_RVALID, icmp_ln11_reg_279)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln11_reg_279 = ap_const_lv1_0) and (m_axi_gmem_hidden_RVALID = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln11_fu_136_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln11_fu_136_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln11_reg_279, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln11_reg_279 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_82)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_82;
        end if; 
    end process;


    gmem_hidden_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_hidden_RVALID, icmp_ln11_reg_279, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln11_reg_279 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem_hidden_blk_n_R <= m_axi_gmem_hidden_RVALID;
        else 
            gmem_hidden_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln11_fu_136_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv13_1800) else "0";
    icmp_ln13_fu_171_p2 <= "1" when (p_fu_74 = ap_const_lv6_30) else "0";
    m_axi_gmem_hidden_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_hidden_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_hidden_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_hidden_ARID <= ap_const_lv1_0;
    m_axi_gmem_hidden_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_hidden_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_hidden_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_hidden_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_hidden_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_hidden_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_hidden_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_hidden_ARVALID <= ap_const_logic_0;
    m_axi_gmem_hidden_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_hidden_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_hidden_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_hidden_AWID <= ap_const_lv1_0;
    m_axi_gmem_hidden_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_hidden_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_hidden_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_hidden_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_hidden_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_hidden_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_hidden_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_hidden_AWVALID <= ap_const_logic_0;
    m_axi_gmem_hidden_BREADY <= ap_const_logic_0;

    m_axi_gmem_hidden_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln11_reg_279, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln11_reg_279 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem_hidden_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_hidden_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_hidden_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem_hidden_WID <= ap_const_lv1_0;
    m_axi_gmem_hidden_WLAST <= ap_const_logic_0;
    m_axi_gmem_hidden_WSTRB <= ap_const_lv64_0;
    m_axi_gmem_hidden_WUSER <= ap_const_lv1_0;
    m_axi_gmem_hidden_WVALID <= ap_const_logic_0;
    residual_address1 <= zext_ln21_2_fu_249_p1(13 - 1 downto 0);

    residual_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            residual_ce1 <= ap_const_logic_1;
        else 
            residual_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    residual_d1 <= t_reg_288;

    residual_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            residual_we1 <= ap_const_logic_1;
        else 
            residual_we1 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln11_1_fu_185_p3 <= 
        add_ln11_fu_165_p2 when (icmp_ln13_fu_171_p2(0) = '1') else 
        s_fu_78;
    select_ln11_fu_177_p3 <= 
        ap_const_lv6_0 when (icmp_ln13_fu_171_p2(0) = '1') else 
        p_fu_74;
    sub_ln21_fu_217_p2 <= std_logic_vector(unsigned(tmp_fu_197_p3) - unsigned(zext_ln21_fu_213_p1));
    tmp_fu_197_p3 <= (trunc_ln21_fu_193_p1 & ap_const_lv6_0);
    tmp_s_fu_205_p3 <= (select_ln11_1_fu_185_p3 & ap_const_lv4_0);
    trunc_ln21_fu_193_p1 <= select_ln11_1_fu_185_p3(7 - 1 downto 0);
    zext_ln21_1_fu_223_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln11_fu_177_p3),13));
    zext_ln21_2_fu_249_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln21_reg_283),64));
    zext_ln21_fu_213_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_205_p3),13));
end behav;
