// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bert_attn_out_norm_residual_kernel_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bias_tile_address0,
        bias_tile_ce0,
        bias_tile_q0,
        tile,
        projected_address1,
        projected_ce1,
        projected_we1,
        projected_d1,
        bias_tile_1_address0,
        bias_tile_1_ce0,
        bias_tile_1_q0,
        bias_tile_2_address0,
        bias_tile_2_ce0,
        bias_tile_2_q0,
        bias_tile_3_address0,
        bias_tile_3_ce0,
        bias_tile_3_q0,
        bias_tile_4_address0,
        bias_tile_4_ce0,
        bias_tile_4_q0,
        bias_tile_5_address0,
        bias_tile_5_ce0,
        bias_tile_5_q0,
        bias_tile_6_address0,
        bias_tile_6_ce0,
        bias_tile_6_q0,
        bias_tile_7_address0,
        bias_tile_7_ce0,
        bias_tile_7_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1:0] bias_tile_address0;
output   bias_tile_ce0;
input  [31:0] bias_tile_q0;
input  [4:0] tile;
output  [13:0] projected_address1;
output   projected_ce1;
output   projected_we1;
output  [255:0] projected_d1;
output  [1:0] bias_tile_1_address0;
output   bias_tile_1_ce0;
input  [31:0] bias_tile_1_q0;
output  [1:0] bias_tile_2_address0;
output   bias_tile_2_ce0;
input  [31:0] bias_tile_2_q0;
output  [1:0] bias_tile_3_address0;
output   bias_tile_3_ce0;
input  [31:0] bias_tile_3_q0;
output  [1:0] bias_tile_4_address0;
output   bias_tile_4_ce0;
input  [31:0] bias_tile_4_q0;
output  [1:0] bias_tile_5_address0;
output   bias_tile_5_ce0;
input  [31:0] bias_tile_5_q0;
output  [1:0] bias_tile_6_address0;
output   bias_tile_6_ce0;
input  [31:0] bias_tile_6_q0;
output  [1:0] bias_tile_7_address0;
output   bias_tile_7_ce0;
input  [31:0] bias_tile_7_q0;

reg ap_idle;
reg bias_tile_ce0;
reg projected_ce1;
reg projected_we1;
reg bias_tile_1_ce0;
reg bias_tile_2_ce0;
reg bias_tile_3_ce0;
reg bias_tile_4_ce0;
reg bias_tile_5_ce0;
reg bias_tile_6_ce0;
reg bias_tile_7_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln83_fu_243_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_1_fu_258_p3;
reg   [0:0] tmp_1_reg_458;
wire   [1:0] lshr_ln_fu_274_p4;
reg   [1:0] lshr_ln_reg_463;
reg   [31:0] bias_tile_load_reg_508;
wire   [13:0] add_ln90_fu_368_p2;
reg   [13:0] add_ln90_reg_513;
reg   [31:0] bias_tile_1_load_reg_518;
reg   [31:0] bias_tile_2_load_reg_523;
reg   [31:0] bias_tile_3_load_reg_528;
reg   [31:0] bias_tile_4_load_reg_533;
reg   [31:0] bias_tile_5_load_reg_538;
reg   [31:0] bias_tile_6_load_reg_543;
reg   [31:0] bias_tile_7_load_reg_548;
wire   [63:0] zext_ln90_fu_284_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln90_3_fu_379_p1;
reg   [5:0] o_fu_86;
wire   [5:0] add_ln85_fu_296_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_o_load;
reg   [7:0] s_fu_90;
wire   [7:0] select_ln83_1_fu_321_p3;
reg   [9:0] indvar_flatten_fu_94;
wire   [9:0] add_ln83_1_fu_249_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [5:0] select_ln83_fu_266_p3;
wire   [7:0] add_ln83_fu_315_p2;
wire   [6:0] trunc_ln90_fu_328_p1;
wire   [12:0] tmp_91_fu_340_p3;
wire   [13:0] tmp_fu_332_p3;
wire   [13:0] zext_ln90_1_fu_348_p1;
wire   [6:0] add_ln_fu_358_p3;
wire   [13:0] sub_ln90_fu_352_p2;
wire   [13:0] zext_ln90_2_fu_364_p1;
wire   [31:0] bitcast_ln90_7_fu_404_p1;
wire   [31:0] bitcast_ln90_6_fu_401_p1;
wire   [31:0] bitcast_ln90_5_fu_398_p1;
wire   [31:0] bitcast_ln90_4_fu_395_p1;
wire   [31:0] bitcast_ln90_3_fu_392_p1;
wire   [31:0] bitcast_ln90_2_fu_389_p1;
wire   [31:0] bitcast_ln90_1_fu_386_p1;
wire   [31:0] bitcast_ln90_fu_383_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

bert_attn_out_norm_residual_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln83_fu_243_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_94 <= add_ln83_1_fu_249_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_94 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln83_fu_243_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            o_fu_86 <= add_ln85_fu_296_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            o_fu_86 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            s_fu_90 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            s_fu_90 <= select_ln83_1_fu_321_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln90_reg_513 <= add_ln90_fu_368_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        bias_tile_1_load_reg_518 <= bias_tile_1_q0;
        bias_tile_2_load_reg_523 <= bias_tile_2_q0;
        bias_tile_3_load_reg_528 <= bias_tile_3_q0;
        bias_tile_4_load_reg_533 <= bias_tile_4_q0;
        bias_tile_5_load_reg_538 <= bias_tile_5_q0;
        bias_tile_6_load_reg_543 <= bias_tile_6_q0;
        bias_tile_7_load_reg_548 <= bias_tile_7_q0;
        bias_tile_load_reg_508 <= bias_tile_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln83_fu_243_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln_reg_463 <= {{select_ln83_fu_266_p3[4:3]}};
        tmp_1_reg_458 <= ap_sig_allocacmp_o_load[32'd5];
    end
end

always @ (*) begin
    if (((icmp_ln83_fu_243_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_o_load = 6'd0;
    end else begin
        ap_sig_allocacmp_o_load = o_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_tile_1_ce0 = 1'b1;
    end else begin
        bias_tile_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_tile_2_ce0 = 1'b1;
    end else begin
        bias_tile_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_tile_3_ce0 = 1'b1;
    end else begin
        bias_tile_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_tile_4_ce0 = 1'b1;
    end else begin
        bias_tile_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_tile_5_ce0 = 1'b1;
    end else begin
        bias_tile_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_tile_6_ce0 = 1'b1;
    end else begin
        bias_tile_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_tile_7_ce0 = 1'b1;
    end else begin
        bias_tile_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_tile_ce0 = 1'b1;
    end else begin
        bias_tile_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        projected_ce1 = 1'b1;
    end else begin
        projected_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        projected_we1 = 1'b1;
    end else begin
        projected_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln83_1_fu_249_p2 = (ap_sig_allocacmp_indvar_flatten_load + 10'd1);

assign add_ln83_fu_315_p2 = (s_fu_90 + 8'd1);

assign add_ln85_fu_296_p2 = (select_ln83_fu_266_p3 + 6'd8);

assign add_ln90_fu_368_p2 = (sub_ln90_fu_352_p2 + zext_ln90_2_fu_364_p1);

assign add_ln_fu_358_p3 = {{tile}, {lshr_ln_reg_463}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bias_tile_1_address0 = zext_ln90_fu_284_p1;

assign bias_tile_2_address0 = zext_ln90_fu_284_p1;

assign bias_tile_3_address0 = zext_ln90_fu_284_p1;

assign bias_tile_4_address0 = zext_ln90_fu_284_p1;

assign bias_tile_5_address0 = zext_ln90_fu_284_p1;

assign bias_tile_6_address0 = zext_ln90_fu_284_p1;

assign bias_tile_7_address0 = zext_ln90_fu_284_p1;

assign bias_tile_address0 = zext_ln90_fu_284_p1;

assign bitcast_ln90_1_fu_386_p1 = bias_tile_1_load_reg_518;

assign bitcast_ln90_2_fu_389_p1 = bias_tile_2_load_reg_523;

assign bitcast_ln90_3_fu_392_p1 = bias_tile_3_load_reg_528;

assign bitcast_ln90_4_fu_395_p1 = bias_tile_4_load_reg_533;

assign bitcast_ln90_5_fu_398_p1 = bias_tile_5_load_reg_538;

assign bitcast_ln90_6_fu_401_p1 = bias_tile_6_load_reg_543;

assign bitcast_ln90_7_fu_404_p1 = bias_tile_7_load_reg_548;

assign bitcast_ln90_fu_383_p1 = bias_tile_load_reg_508;

assign icmp_ln83_fu_243_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 10'd512) ? 1'b1 : 1'b0);

assign lshr_ln_fu_274_p4 = {{select_ln83_fu_266_p3[4:3]}};

assign projected_address1 = zext_ln90_3_fu_379_p1;

assign projected_d1 = {{{{{{{{bitcast_ln90_7_fu_404_p1}, {bitcast_ln90_6_fu_401_p1}}, {bitcast_ln90_5_fu_398_p1}}, {bitcast_ln90_4_fu_395_p1}}, {bitcast_ln90_3_fu_392_p1}}, {bitcast_ln90_2_fu_389_p1}}, {bitcast_ln90_1_fu_386_p1}}, {bitcast_ln90_fu_383_p1}};

assign select_ln83_1_fu_321_p3 = ((tmp_1_reg_458[0:0] == 1'b1) ? add_ln83_fu_315_p2 : s_fu_90);

assign select_ln83_fu_266_p3 = ((tmp_1_fu_258_p3[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_o_load);

assign sub_ln90_fu_352_p2 = (tmp_fu_332_p3 - zext_ln90_1_fu_348_p1);

assign tmp_1_fu_258_p3 = ap_sig_allocacmp_o_load[32'd5];

assign tmp_91_fu_340_p3 = {{select_ln83_1_fu_321_p3}, {5'd0}};

assign tmp_fu_332_p3 = {{trunc_ln90_fu_328_p1}, {7'd0}};

assign trunc_ln90_fu_328_p1 = select_ln83_1_fu_321_p3[6:0];

assign zext_ln90_1_fu_348_p1 = tmp_91_fu_340_p3;

assign zext_ln90_2_fu_364_p1 = add_ln_fu_358_p3;

assign zext_ln90_3_fu_379_p1 = add_ln90_reg_513;

assign zext_ln90_fu_284_p1 = lshr_ln_fu_274_p4;

endmodule //bert_attn_out_norm_residual_kernel_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT
