// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bert_attn_out_norm_residual_kernel_load_output_bias32 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_o_AWVALID,
        m_axi_gmem_o_AWREADY,
        m_axi_gmem_o_AWADDR,
        m_axi_gmem_o_AWID,
        m_axi_gmem_o_AWLEN,
        m_axi_gmem_o_AWSIZE,
        m_axi_gmem_o_AWBURST,
        m_axi_gmem_o_AWLOCK,
        m_axi_gmem_o_AWCACHE,
        m_axi_gmem_o_AWPROT,
        m_axi_gmem_o_AWQOS,
        m_axi_gmem_o_AWREGION,
        m_axi_gmem_o_AWUSER,
        m_axi_gmem_o_WVALID,
        m_axi_gmem_o_WREADY,
        m_axi_gmem_o_WDATA,
        m_axi_gmem_o_WSTRB,
        m_axi_gmem_o_WLAST,
        m_axi_gmem_o_WID,
        m_axi_gmem_o_WUSER,
        m_axi_gmem_o_ARVALID,
        m_axi_gmem_o_ARREADY,
        m_axi_gmem_o_ARADDR,
        m_axi_gmem_o_ARID,
        m_axi_gmem_o_ARLEN,
        m_axi_gmem_o_ARSIZE,
        m_axi_gmem_o_ARBURST,
        m_axi_gmem_o_ARLOCK,
        m_axi_gmem_o_ARCACHE,
        m_axi_gmem_o_ARPROT,
        m_axi_gmem_o_ARQOS,
        m_axi_gmem_o_ARREGION,
        m_axi_gmem_o_ARUSER,
        m_axi_gmem_o_RVALID,
        m_axi_gmem_o_RREADY,
        m_axi_gmem_o_RDATA,
        m_axi_gmem_o_RLAST,
        m_axi_gmem_o_RID,
        m_axi_gmem_o_RFIFONUM,
        m_axi_gmem_o_RUSER,
        m_axi_gmem_o_RRESP,
        m_axi_gmem_o_BVALID,
        m_axi_gmem_o_BREADY,
        m_axi_gmem_o_BRESP,
        m_axi_gmem_o_BID,
        m_axi_gmem_o_BUSER,
        bias,
        out_base,
        bias_tile_0_address0,
        bias_tile_0_ce0,
        bias_tile_0_we0,
        bias_tile_0_d0,
        bias_tile_0_address1,
        bias_tile_0_ce1,
        bias_tile_0_we1,
        bias_tile_0_d1,
        bias_tile_1_address0,
        bias_tile_1_ce0,
        bias_tile_1_we0,
        bias_tile_1_d0,
        bias_tile_1_address1,
        bias_tile_1_ce1,
        bias_tile_1_we1,
        bias_tile_1_d1,
        bias_tile_2_address0,
        bias_tile_2_ce0,
        bias_tile_2_we0,
        bias_tile_2_d0,
        bias_tile_2_address1,
        bias_tile_2_ce1,
        bias_tile_2_we1,
        bias_tile_2_d1,
        bias_tile_3_address0,
        bias_tile_3_ce0,
        bias_tile_3_we0,
        bias_tile_3_d0,
        bias_tile_3_address1,
        bias_tile_3_ce1,
        bias_tile_3_we1,
        bias_tile_3_d1,
        bias_tile_4_address0,
        bias_tile_4_ce0,
        bias_tile_4_we0,
        bias_tile_4_d0,
        bias_tile_4_address1,
        bias_tile_4_ce1,
        bias_tile_4_we1,
        bias_tile_4_d1,
        bias_tile_5_address0,
        bias_tile_5_ce0,
        bias_tile_5_we0,
        bias_tile_5_d0,
        bias_tile_5_address1,
        bias_tile_5_ce1,
        bias_tile_5_we1,
        bias_tile_5_d1,
        bias_tile_6_address0,
        bias_tile_6_ce0,
        bias_tile_6_we0,
        bias_tile_6_d0,
        bias_tile_6_address1,
        bias_tile_6_ce1,
        bias_tile_6_we1,
        bias_tile_6_d1,
        bias_tile_7_address0,
        bias_tile_7_ce0,
        bias_tile_7_we0,
        bias_tile_7_d0,
        bias_tile_7_address1,
        bias_tile_7_ce1,
        bias_tile_7_we1,
        bias_tile_7_d1
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_o_AWVALID;
input   m_axi_gmem_o_AWREADY;
output  [63:0] m_axi_gmem_o_AWADDR;
output  [0:0] m_axi_gmem_o_AWID;
output  [31:0] m_axi_gmem_o_AWLEN;
output  [2:0] m_axi_gmem_o_AWSIZE;
output  [1:0] m_axi_gmem_o_AWBURST;
output  [1:0] m_axi_gmem_o_AWLOCK;
output  [3:0] m_axi_gmem_o_AWCACHE;
output  [2:0] m_axi_gmem_o_AWPROT;
output  [3:0] m_axi_gmem_o_AWQOS;
output  [3:0] m_axi_gmem_o_AWREGION;
output  [0:0] m_axi_gmem_o_AWUSER;
output   m_axi_gmem_o_WVALID;
input   m_axi_gmem_o_WREADY;
output  [511:0] m_axi_gmem_o_WDATA;
output  [63:0] m_axi_gmem_o_WSTRB;
output   m_axi_gmem_o_WLAST;
output  [0:0] m_axi_gmem_o_WID;
output  [0:0] m_axi_gmem_o_WUSER;
output   m_axi_gmem_o_ARVALID;
input   m_axi_gmem_o_ARREADY;
output  [63:0] m_axi_gmem_o_ARADDR;
output  [0:0] m_axi_gmem_o_ARID;
output  [31:0] m_axi_gmem_o_ARLEN;
output  [2:0] m_axi_gmem_o_ARSIZE;
output  [1:0] m_axi_gmem_o_ARBURST;
output  [1:0] m_axi_gmem_o_ARLOCK;
output  [3:0] m_axi_gmem_o_ARCACHE;
output  [2:0] m_axi_gmem_o_ARPROT;
output  [3:0] m_axi_gmem_o_ARQOS;
output  [3:0] m_axi_gmem_o_ARREGION;
output  [0:0] m_axi_gmem_o_ARUSER;
input   m_axi_gmem_o_RVALID;
output   m_axi_gmem_o_RREADY;
input  [511:0] m_axi_gmem_o_RDATA;
input   m_axi_gmem_o_RLAST;
input  [0:0] m_axi_gmem_o_RID;
input  [8:0] m_axi_gmem_o_RFIFONUM;
input  [0:0] m_axi_gmem_o_RUSER;
input  [1:0] m_axi_gmem_o_RRESP;
input   m_axi_gmem_o_BVALID;
output   m_axi_gmem_o_BREADY;
input  [1:0] m_axi_gmem_o_BRESP;
input  [0:0] m_axi_gmem_o_BID;
input  [0:0] m_axi_gmem_o_BUSER;
input  [63:0] bias;
input  [9:0] out_base;
output  [1:0] bias_tile_0_address0;
output   bias_tile_0_ce0;
output   bias_tile_0_we0;
output  [31:0] bias_tile_0_d0;
output  [1:0] bias_tile_0_address1;
output   bias_tile_0_ce1;
output   bias_tile_0_we1;
output  [31:0] bias_tile_0_d1;
output  [1:0] bias_tile_1_address0;
output   bias_tile_1_ce0;
output   bias_tile_1_we0;
output  [31:0] bias_tile_1_d0;
output  [1:0] bias_tile_1_address1;
output   bias_tile_1_ce1;
output   bias_tile_1_we1;
output  [31:0] bias_tile_1_d1;
output  [1:0] bias_tile_2_address0;
output   bias_tile_2_ce0;
output   bias_tile_2_we0;
output  [31:0] bias_tile_2_d0;
output  [1:0] bias_tile_2_address1;
output   bias_tile_2_ce1;
output   bias_tile_2_we1;
output  [31:0] bias_tile_2_d1;
output  [1:0] bias_tile_3_address0;
output   bias_tile_3_ce0;
output   bias_tile_3_we0;
output  [31:0] bias_tile_3_d0;
output  [1:0] bias_tile_3_address1;
output   bias_tile_3_ce1;
output   bias_tile_3_we1;
output  [31:0] bias_tile_3_d1;
output  [1:0] bias_tile_4_address0;
output   bias_tile_4_ce0;
output   bias_tile_4_we0;
output  [31:0] bias_tile_4_d0;
output  [1:0] bias_tile_4_address1;
output   bias_tile_4_ce1;
output   bias_tile_4_we1;
output  [31:0] bias_tile_4_d1;
output  [1:0] bias_tile_5_address0;
output   bias_tile_5_ce0;
output   bias_tile_5_we0;
output  [31:0] bias_tile_5_d0;
output  [1:0] bias_tile_5_address1;
output   bias_tile_5_ce1;
output   bias_tile_5_we1;
output  [31:0] bias_tile_5_d1;
output  [1:0] bias_tile_6_address0;
output   bias_tile_6_ce0;
output   bias_tile_6_we0;
output  [31:0] bias_tile_6_d0;
output  [1:0] bias_tile_6_address1;
output   bias_tile_6_ce1;
output   bias_tile_6_we1;
output  [31:0] bias_tile_6_d1;
output  [1:0] bias_tile_7_address0;
output   bias_tile_7_ce0;
output   bias_tile_7_we0;
output  [31:0] bias_tile_7_d0;
output  [1:0] bias_tile_7_address1;
output   bias_tile_7_ce1;
output   bias_tile_7_we1;
output  [31:0] bias_tile_7_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_o_ARVALID;
reg[63:0] m_axi_gmem_o_ARADDR;
reg[0:0] m_axi_gmem_o_ARID;
reg[31:0] m_axi_gmem_o_ARLEN;
reg[2:0] m_axi_gmem_o_ARSIZE;
reg[1:0] m_axi_gmem_o_ARBURST;
reg[1:0] m_axi_gmem_o_ARLOCK;
reg[3:0] m_axi_gmem_o_ARCACHE;
reg[2:0] m_axi_gmem_o_ARPROT;
reg[3:0] m_axi_gmem_o_ARQOS;
reg[3:0] m_axi_gmem_o_ARREGION;
reg[0:0] m_axi_gmem_o_ARUSER;
reg m_axi_gmem_o_RREADY;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem_o_blk_n_AR;
wire    ap_CS_fsm_state2;
reg   [57:0] trunc_ln_reg_156;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_start;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_done;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_idle;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_ready;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWVALID;
wire   [63:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWADDR;
wire   [0:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWID;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWLEN;
wire   [2:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWSIZE;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWBURST;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWLOCK;
wire   [3:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWCACHE;
wire   [2:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWPROT;
wire   [3:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWQOS;
wire   [3:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWREGION;
wire   [0:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWUSER;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_WVALID;
wire   [511:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_WDATA;
wire   [63:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_WSTRB;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_WLAST;
wire   [0:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_WID;
wire   [0:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_WUSER;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARVALID;
wire   [63:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARADDR;
wire   [0:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARID;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARLEN;
wire   [2:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARSIZE;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARBURST;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARLOCK;
wire   [3:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARCACHE;
wire   [2:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARPROT;
wire   [3:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARQOS;
wire   [3:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARREGION;
wire   [0:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARUSER;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_RREADY;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_BREADY;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_address0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_ce0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_we0;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_d0;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_address1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_ce1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_we1;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_d1;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_address0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_ce0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_we0;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_d0;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_address1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_ce1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_we1;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_d1;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_address0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_ce0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_we0;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_d0;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_address1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_ce1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_we1;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_d1;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_address0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_ce0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_we0;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_d0;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_address1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_ce1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_we1;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_d1;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_address0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_ce0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_we0;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_d0;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_address1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_ce1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_we1;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_d1;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_address0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_ce0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_we0;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_d0;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_address1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_ce1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_we1;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_d1;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_address0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_ce0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_we0;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_d0;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_address1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_ce1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_we1;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_d1;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_address0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_ce0;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_we0;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_d0;
wire   [1:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_address1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_ce1;
wire    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_we1;
wire   [31:0] grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_d1;
reg    grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire  signed [63:0] sext_ln56_fu_146_p1;
wire   [5:0] tmp_fu_108_p4;
wire   [11:0] shl_ln_fu_118_p3;
wire   [63:0] zext_ln56_fu_126_p1;
wire   [63:0] add_ln56_fu_130_p2;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_start_reg = 1'b0;
end

bert_attn_out_norm_residual_kernel_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_start),
    .ap_done(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_done),
    .ap_idle(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_idle),
    .ap_ready(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_ready),
    .m_axi_gmem_o_AWVALID(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWVALID),
    .m_axi_gmem_o_AWREADY(1'b0),
    .m_axi_gmem_o_AWADDR(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWADDR),
    .m_axi_gmem_o_AWID(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWID),
    .m_axi_gmem_o_AWLEN(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWLEN),
    .m_axi_gmem_o_AWSIZE(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWSIZE),
    .m_axi_gmem_o_AWBURST(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWBURST),
    .m_axi_gmem_o_AWLOCK(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWLOCK),
    .m_axi_gmem_o_AWCACHE(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWCACHE),
    .m_axi_gmem_o_AWPROT(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWPROT),
    .m_axi_gmem_o_AWQOS(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWQOS),
    .m_axi_gmem_o_AWREGION(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWREGION),
    .m_axi_gmem_o_AWUSER(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_AWUSER),
    .m_axi_gmem_o_WVALID(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_WVALID),
    .m_axi_gmem_o_WREADY(1'b0),
    .m_axi_gmem_o_WDATA(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_WDATA),
    .m_axi_gmem_o_WSTRB(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_WSTRB),
    .m_axi_gmem_o_WLAST(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_WLAST),
    .m_axi_gmem_o_WID(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_WID),
    .m_axi_gmem_o_WUSER(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_WUSER),
    .m_axi_gmem_o_ARVALID(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARVALID),
    .m_axi_gmem_o_ARREADY(m_axi_gmem_o_ARREADY),
    .m_axi_gmem_o_ARADDR(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARADDR),
    .m_axi_gmem_o_ARID(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARID),
    .m_axi_gmem_o_ARLEN(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARLEN),
    .m_axi_gmem_o_ARSIZE(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARSIZE),
    .m_axi_gmem_o_ARBURST(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARBURST),
    .m_axi_gmem_o_ARLOCK(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARLOCK),
    .m_axi_gmem_o_ARCACHE(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARCACHE),
    .m_axi_gmem_o_ARPROT(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARPROT),
    .m_axi_gmem_o_ARQOS(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARQOS),
    .m_axi_gmem_o_ARREGION(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARREGION),
    .m_axi_gmem_o_ARUSER(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARUSER),
    .m_axi_gmem_o_RVALID(m_axi_gmem_o_RVALID),
    .m_axi_gmem_o_RREADY(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_RREADY),
    .m_axi_gmem_o_RDATA(m_axi_gmem_o_RDATA),
    .m_axi_gmem_o_RLAST(m_axi_gmem_o_RLAST),
    .m_axi_gmem_o_RID(m_axi_gmem_o_RID),
    .m_axi_gmem_o_RFIFONUM(m_axi_gmem_o_RFIFONUM),
    .m_axi_gmem_o_RUSER(m_axi_gmem_o_RUSER),
    .m_axi_gmem_o_RRESP(m_axi_gmem_o_RRESP),
    .m_axi_gmem_o_BVALID(1'b0),
    .m_axi_gmem_o_BREADY(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_BREADY),
    .m_axi_gmem_o_BRESP(2'd0),
    .m_axi_gmem_o_BID(1'd0),
    .m_axi_gmem_o_BUSER(1'd0),
    .sext_ln56(trunc_ln_reg_156),
    .bias_tile_7_address0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_address0),
    .bias_tile_7_ce0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_ce0),
    .bias_tile_7_we0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_we0),
    .bias_tile_7_d0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_d0),
    .bias_tile_7_address1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_address1),
    .bias_tile_7_ce1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_ce1),
    .bias_tile_7_we1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_we1),
    .bias_tile_7_d1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_d1),
    .bias_tile_6_address0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_address0),
    .bias_tile_6_ce0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_ce0),
    .bias_tile_6_we0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_we0),
    .bias_tile_6_d0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_d0),
    .bias_tile_6_address1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_address1),
    .bias_tile_6_ce1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_ce1),
    .bias_tile_6_we1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_we1),
    .bias_tile_6_d1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_d1),
    .bias_tile_5_address0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_address0),
    .bias_tile_5_ce0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_ce0),
    .bias_tile_5_we0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_we0),
    .bias_tile_5_d0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_d0),
    .bias_tile_5_address1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_address1),
    .bias_tile_5_ce1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_ce1),
    .bias_tile_5_we1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_we1),
    .bias_tile_5_d1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_d1),
    .bias_tile_4_address0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_address0),
    .bias_tile_4_ce0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_ce0),
    .bias_tile_4_we0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_we0),
    .bias_tile_4_d0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_d0),
    .bias_tile_4_address1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_address1),
    .bias_tile_4_ce1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_ce1),
    .bias_tile_4_we1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_we1),
    .bias_tile_4_d1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_d1),
    .bias_tile_3_address0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_address0),
    .bias_tile_3_ce0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_ce0),
    .bias_tile_3_we0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_we0),
    .bias_tile_3_d0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_d0),
    .bias_tile_3_address1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_address1),
    .bias_tile_3_ce1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_ce1),
    .bias_tile_3_we1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_we1),
    .bias_tile_3_d1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_d1),
    .bias_tile_2_address0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_address0),
    .bias_tile_2_ce0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_ce0),
    .bias_tile_2_we0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_we0),
    .bias_tile_2_d0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_d0),
    .bias_tile_2_address1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_address1),
    .bias_tile_2_ce1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_ce1),
    .bias_tile_2_we1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_we1),
    .bias_tile_2_d1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_d1),
    .bias_tile_1_address0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_address0),
    .bias_tile_1_ce0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_ce0),
    .bias_tile_1_we0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_we0),
    .bias_tile_1_d0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_d0),
    .bias_tile_1_address1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_address1),
    .bias_tile_1_ce1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_ce1),
    .bias_tile_1_we1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_we1),
    .bias_tile_1_d1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_d1),
    .bias_tile_0_address0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_address0),
    .bias_tile_0_ce0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_ce0),
    .bias_tile_0_we0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_we0),
    .bias_tile_0_d0(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_d0),
    .bias_tile_0_address1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_address1),
    .bias_tile_0_ce1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_ce1),
    .bias_tile_0_we1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_we1),
    .bias_tile_0_d1(grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_start_reg <= 1'b1;
        end else if ((grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_ready == 1'b1)) begin
            grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln_reg_156 <= {{add_ln56_fu_130_p2[63:6]}};
    end
end

always @ (*) begin
    if ((grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_o_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state10) & (grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem_o_blk_n_AR = m_axi_gmem_o_ARREADY;
    end else begin
        gmem_o_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((m_axi_gmem_o_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_o_ARADDR = sext_ln56_fu_146_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_ARADDR = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARADDR;
    end else begin
        m_axi_gmem_o_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_ARBURST = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARBURST;
    end else begin
        m_axi_gmem_o_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_ARCACHE = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARCACHE;
    end else begin
        m_axi_gmem_o_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_ARID = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARID;
    end else begin
        m_axi_gmem_o_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_o_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_o_ARLEN = 32'd2;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_ARLEN = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARLEN;
    end else begin
        m_axi_gmem_o_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_ARLOCK = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARLOCK;
    end else begin
        m_axi_gmem_o_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_ARPROT = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARPROT;
    end else begin
        m_axi_gmem_o_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_ARQOS = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARQOS;
    end else begin
        m_axi_gmem_o_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_ARREGION = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARREGION;
    end else begin
        m_axi_gmem_o_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_ARSIZE = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARSIZE;
    end else begin
        m_axi_gmem_o_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_ARUSER = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARUSER;
    end else begin
        m_axi_gmem_o_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_o_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_o_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_ARVALID = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_ARVALID;
    end else begin
        m_axi_gmem_o_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_o_RREADY = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_m_axi_gmem_o_RREADY;
    end else begin
        m_axi_gmem_o_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((m_axi_gmem_o_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln56_fu_130_p2 = (zext_ln56_fu_126_p1 + bias);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bias_tile_0_address0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_address0;

assign bias_tile_0_address1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_address1;

assign bias_tile_0_ce0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_ce0;

assign bias_tile_0_ce1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_ce1;

assign bias_tile_0_d0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_d0;

assign bias_tile_0_d1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_d1;

assign bias_tile_0_we0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_we0;

assign bias_tile_0_we1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_0_we1;

assign bias_tile_1_address0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_address0;

assign bias_tile_1_address1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_address1;

assign bias_tile_1_ce0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_ce0;

assign bias_tile_1_ce1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_ce1;

assign bias_tile_1_d0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_d0;

assign bias_tile_1_d1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_d1;

assign bias_tile_1_we0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_we0;

assign bias_tile_1_we1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_1_we1;

assign bias_tile_2_address0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_address0;

assign bias_tile_2_address1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_address1;

assign bias_tile_2_ce0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_ce0;

assign bias_tile_2_ce1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_ce1;

assign bias_tile_2_d0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_d0;

assign bias_tile_2_d1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_d1;

assign bias_tile_2_we0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_we0;

assign bias_tile_2_we1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_2_we1;

assign bias_tile_3_address0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_address0;

assign bias_tile_3_address1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_address1;

assign bias_tile_3_ce0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_ce0;

assign bias_tile_3_ce1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_ce1;

assign bias_tile_3_d0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_d0;

assign bias_tile_3_d1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_d1;

assign bias_tile_3_we0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_we0;

assign bias_tile_3_we1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_3_we1;

assign bias_tile_4_address0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_address0;

assign bias_tile_4_address1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_address1;

assign bias_tile_4_ce0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_ce0;

assign bias_tile_4_ce1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_ce1;

assign bias_tile_4_d0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_d0;

assign bias_tile_4_d1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_d1;

assign bias_tile_4_we0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_we0;

assign bias_tile_4_we1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_4_we1;

assign bias_tile_5_address0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_address0;

assign bias_tile_5_address1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_address1;

assign bias_tile_5_ce0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_ce0;

assign bias_tile_5_ce1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_ce1;

assign bias_tile_5_d0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_d0;

assign bias_tile_5_d1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_d1;

assign bias_tile_5_we0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_we0;

assign bias_tile_5_we1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_5_we1;

assign bias_tile_6_address0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_address0;

assign bias_tile_6_address1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_address1;

assign bias_tile_6_ce0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_ce0;

assign bias_tile_6_ce1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_ce1;

assign bias_tile_6_d0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_d0;

assign bias_tile_6_d1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_d1;

assign bias_tile_6_we0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_we0;

assign bias_tile_6_we1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_6_we1;

assign bias_tile_7_address0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_address0;

assign bias_tile_7_address1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_address1;

assign bias_tile_7_ce0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_ce0;

assign bias_tile_7_ce1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_ce1;

assign bias_tile_7_d0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_d0;

assign bias_tile_7_d1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_d1;

assign bias_tile_7_we0 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_we0;

assign bias_tile_7_we1 = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_bias_tile_7_we1;

assign grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_start = grp_load_output_bias32_Pipeline_LOAD_OUT_BIAS_PACK_fu_85_ap_start_reg;

assign m_axi_gmem_o_AWADDR = 64'd0;

assign m_axi_gmem_o_AWBURST = 2'd0;

assign m_axi_gmem_o_AWCACHE = 4'd0;

assign m_axi_gmem_o_AWID = 1'd0;

assign m_axi_gmem_o_AWLEN = 32'd0;

assign m_axi_gmem_o_AWLOCK = 2'd0;

assign m_axi_gmem_o_AWPROT = 3'd0;

assign m_axi_gmem_o_AWQOS = 4'd0;

assign m_axi_gmem_o_AWREGION = 4'd0;

assign m_axi_gmem_o_AWSIZE = 3'd0;

assign m_axi_gmem_o_AWUSER = 1'd0;

assign m_axi_gmem_o_AWVALID = 1'b0;

assign m_axi_gmem_o_BREADY = 1'b0;

assign m_axi_gmem_o_WDATA = 512'd0;

assign m_axi_gmem_o_WID = 1'd0;

assign m_axi_gmem_o_WLAST = 1'b0;

assign m_axi_gmem_o_WSTRB = 64'd0;

assign m_axi_gmem_o_WUSER = 1'd0;

assign m_axi_gmem_o_WVALID = 1'b0;

assign sext_ln56_fu_146_p1 = $signed(trunc_ln_reg_156);

assign shl_ln_fu_118_p3 = {{tmp_fu_108_p4}, {6'd0}};

assign tmp_fu_108_p4 = {{out_base[9:4]}};

assign zext_ln56_fu_126_p1 = shl_ln_fu_118_p3;

endmodule //bert_attn_out_norm_residual_kernel_load_output_bias32
