// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bert_attn_out_norm_residual_kernel_initialize_projection (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_o_AWVALID,
        m_axi_gmem_o_AWREADY,
        m_axi_gmem_o_AWADDR,
        m_axi_gmem_o_AWID,
        m_axi_gmem_o_AWLEN,
        m_axi_gmem_o_AWSIZE,
        m_axi_gmem_o_AWBURST,
        m_axi_gmem_o_AWLOCK,
        m_axi_gmem_o_AWCACHE,
        m_axi_gmem_o_AWPROT,
        m_axi_gmem_o_AWQOS,
        m_axi_gmem_o_AWREGION,
        m_axi_gmem_o_AWUSER,
        m_axi_gmem_o_WVALID,
        m_axi_gmem_o_WREADY,
        m_axi_gmem_o_WDATA,
        m_axi_gmem_o_WSTRB,
        m_axi_gmem_o_WLAST,
        m_axi_gmem_o_WID,
        m_axi_gmem_o_WUSER,
        m_axi_gmem_o_ARVALID,
        m_axi_gmem_o_ARREADY,
        m_axi_gmem_o_ARADDR,
        m_axi_gmem_o_ARID,
        m_axi_gmem_o_ARLEN,
        m_axi_gmem_o_ARSIZE,
        m_axi_gmem_o_ARBURST,
        m_axi_gmem_o_ARLOCK,
        m_axi_gmem_o_ARCACHE,
        m_axi_gmem_o_ARPROT,
        m_axi_gmem_o_ARQOS,
        m_axi_gmem_o_ARREGION,
        m_axi_gmem_o_ARUSER,
        m_axi_gmem_o_RVALID,
        m_axi_gmem_o_RREADY,
        m_axi_gmem_o_RDATA,
        m_axi_gmem_o_RLAST,
        m_axi_gmem_o_RID,
        m_axi_gmem_o_RFIFONUM,
        m_axi_gmem_o_RUSER,
        m_axi_gmem_o_RRESP,
        m_axi_gmem_o_BVALID,
        m_axi_gmem_o_BREADY,
        m_axi_gmem_o_BRESP,
        m_axi_gmem_o_BID,
        m_axi_gmem_o_BUSER,
        bias,
        projected_address1,
        projected_ce1,
        projected_we1,
        projected_d1
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_o_AWVALID;
input   m_axi_gmem_o_AWREADY;
output  [63:0] m_axi_gmem_o_AWADDR;
output  [0:0] m_axi_gmem_o_AWID;
output  [31:0] m_axi_gmem_o_AWLEN;
output  [2:0] m_axi_gmem_o_AWSIZE;
output  [1:0] m_axi_gmem_o_AWBURST;
output  [1:0] m_axi_gmem_o_AWLOCK;
output  [3:0] m_axi_gmem_o_AWCACHE;
output  [2:0] m_axi_gmem_o_AWPROT;
output  [3:0] m_axi_gmem_o_AWQOS;
output  [3:0] m_axi_gmem_o_AWREGION;
output  [0:0] m_axi_gmem_o_AWUSER;
output   m_axi_gmem_o_WVALID;
input   m_axi_gmem_o_WREADY;
output  [511:0] m_axi_gmem_o_WDATA;
output  [63:0] m_axi_gmem_o_WSTRB;
output   m_axi_gmem_o_WLAST;
output  [0:0] m_axi_gmem_o_WID;
output  [0:0] m_axi_gmem_o_WUSER;
output   m_axi_gmem_o_ARVALID;
input   m_axi_gmem_o_ARREADY;
output  [63:0] m_axi_gmem_o_ARADDR;
output  [0:0] m_axi_gmem_o_ARID;
output  [31:0] m_axi_gmem_o_ARLEN;
output  [2:0] m_axi_gmem_o_ARSIZE;
output  [1:0] m_axi_gmem_o_ARBURST;
output  [1:0] m_axi_gmem_o_ARLOCK;
output  [3:0] m_axi_gmem_o_ARCACHE;
output  [2:0] m_axi_gmem_o_ARPROT;
output  [3:0] m_axi_gmem_o_ARQOS;
output  [3:0] m_axi_gmem_o_ARREGION;
output  [0:0] m_axi_gmem_o_ARUSER;
input   m_axi_gmem_o_RVALID;
output   m_axi_gmem_o_RREADY;
input  [511:0] m_axi_gmem_o_RDATA;
input   m_axi_gmem_o_RLAST;
input  [0:0] m_axi_gmem_o_RID;
input  [8:0] m_axi_gmem_o_RFIFONUM;
input  [0:0] m_axi_gmem_o_RUSER;
input  [1:0] m_axi_gmem_o_RRESP;
input   m_axi_gmem_o_BVALID;
output   m_axi_gmem_o_BREADY;
input  [1:0] m_axi_gmem_o_BRESP;
input  [0:0] m_axi_gmem_o_BID;
input  [0:0] m_axi_gmem_o_BUSER;
input  [63:0] bias;
output  [13:0] projected_address1;
output   projected_ce1;
output   projected_we1;
output  [255:0] projected_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_o_ARVALID;
reg m_axi_gmem_o_RREADY;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [4:0] tile_1_reg_175;
wire    ap_CS_fsm_state2;
wire   [9:0] shl_ln_fu_149_p3;
reg   [9:0] shl_ln_reg_183;
wire   [0:0] icmp_ln79_fu_137_p2;
reg   [1:0] bias_tile_address0;
reg    bias_tile_ce0;
reg    bias_tile_we0;
wire   [31:0] bias_tile_q0;
reg    bias_tile_ce1;
reg    bias_tile_we1;
reg   [1:0] bias_tile_1_address0;
reg    bias_tile_1_ce0;
reg    bias_tile_1_we0;
wire   [31:0] bias_tile_1_q0;
reg    bias_tile_1_ce1;
reg    bias_tile_1_we1;
reg   [1:0] bias_tile_2_address0;
reg    bias_tile_2_ce0;
reg    bias_tile_2_we0;
wire   [31:0] bias_tile_2_q0;
reg    bias_tile_2_ce1;
reg    bias_tile_2_we1;
reg   [1:0] bias_tile_3_address0;
reg    bias_tile_3_ce0;
reg    bias_tile_3_we0;
wire   [31:0] bias_tile_3_q0;
reg    bias_tile_3_ce1;
reg    bias_tile_3_we1;
reg   [1:0] bias_tile_4_address0;
reg    bias_tile_4_ce0;
reg    bias_tile_4_we0;
wire   [31:0] bias_tile_4_q0;
reg    bias_tile_4_ce1;
reg    bias_tile_4_we1;
reg   [1:0] bias_tile_5_address0;
reg    bias_tile_5_ce0;
reg    bias_tile_5_we0;
wire   [31:0] bias_tile_5_q0;
reg    bias_tile_5_ce1;
reg    bias_tile_5_we1;
reg   [1:0] bias_tile_6_address0;
reg    bias_tile_6_ce0;
reg    bias_tile_6_we0;
wire   [31:0] bias_tile_6_q0;
reg    bias_tile_6_ce1;
reg    bias_tile_6_we1;
reg   [1:0] bias_tile_7_address0;
reg    bias_tile_7_ce0;
reg    bias_tile_7_we0;
wire   [31:0] bias_tile_7_q0;
reg    bias_tile_7_ce1;
reg    bias_tile_7_we1;
wire    grp_load_output_bias32_fu_98_ap_start;
wire    grp_load_output_bias32_fu_98_ap_done;
wire    grp_load_output_bias32_fu_98_ap_idle;
wire    grp_load_output_bias32_fu_98_ap_ready;
wire    grp_load_output_bias32_fu_98_m_axi_gmem_o_AWVALID;
wire   [63:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_AWADDR;
wire   [0:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_AWID;
wire   [31:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_AWLEN;
wire   [2:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_AWSIZE;
wire   [1:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_AWBURST;
wire   [1:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_AWLOCK;
wire   [3:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_AWCACHE;
wire   [2:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_AWPROT;
wire   [3:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_AWQOS;
wire   [3:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_AWREGION;
wire   [0:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_AWUSER;
wire    grp_load_output_bias32_fu_98_m_axi_gmem_o_WVALID;
wire   [511:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_WDATA;
wire   [63:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_WSTRB;
wire    grp_load_output_bias32_fu_98_m_axi_gmem_o_WLAST;
wire   [0:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_WID;
wire   [0:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_WUSER;
wire    grp_load_output_bias32_fu_98_m_axi_gmem_o_ARVALID;
wire   [63:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_ARADDR;
wire   [0:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_ARID;
wire   [31:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_ARLEN;
wire   [2:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_ARSIZE;
wire   [1:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_ARBURST;
wire   [1:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_ARLOCK;
wire   [3:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_ARCACHE;
wire   [2:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_ARPROT;
wire   [3:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_ARQOS;
wire   [3:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_ARREGION;
wire   [0:0] grp_load_output_bias32_fu_98_m_axi_gmem_o_ARUSER;
wire    grp_load_output_bias32_fu_98_m_axi_gmem_o_RREADY;
wire    grp_load_output_bias32_fu_98_m_axi_gmem_o_BREADY;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_0_address0;
wire    grp_load_output_bias32_fu_98_bias_tile_0_ce0;
wire    grp_load_output_bias32_fu_98_bias_tile_0_we0;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_0_d0;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_0_address1;
wire    grp_load_output_bias32_fu_98_bias_tile_0_ce1;
wire    grp_load_output_bias32_fu_98_bias_tile_0_we1;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_0_d1;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_1_address0;
wire    grp_load_output_bias32_fu_98_bias_tile_1_ce0;
wire    grp_load_output_bias32_fu_98_bias_tile_1_we0;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_1_d0;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_1_address1;
wire    grp_load_output_bias32_fu_98_bias_tile_1_ce1;
wire    grp_load_output_bias32_fu_98_bias_tile_1_we1;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_1_d1;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_2_address0;
wire    grp_load_output_bias32_fu_98_bias_tile_2_ce0;
wire    grp_load_output_bias32_fu_98_bias_tile_2_we0;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_2_d0;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_2_address1;
wire    grp_load_output_bias32_fu_98_bias_tile_2_ce1;
wire    grp_load_output_bias32_fu_98_bias_tile_2_we1;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_2_d1;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_3_address0;
wire    grp_load_output_bias32_fu_98_bias_tile_3_ce0;
wire    grp_load_output_bias32_fu_98_bias_tile_3_we0;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_3_d0;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_3_address1;
wire    grp_load_output_bias32_fu_98_bias_tile_3_ce1;
wire    grp_load_output_bias32_fu_98_bias_tile_3_we1;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_3_d1;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_4_address0;
wire    grp_load_output_bias32_fu_98_bias_tile_4_ce0;
wire    grp_load_output_bias32_fu_98_bias_tile_4_we0;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_4_d0;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_4_address1;
wire    grp_load_output_bias32_fu_98_bias_tile_4_ce1;
wire    grp_load_output_bias32_fu_98_bias_tile_4_we1;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_4_d1;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_5_address0;
wire    grp_load_output_bias32_fu_98_bias_tile_5_ce0;
wire    grp_load_output_bias32_fu_98_bias_tile_5_we0;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_5_d0;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_5_address1;
wire    grp_load_output_bias32_fu_98_bias_tile_5_ce1;
wire    grp_load_output_bias32_fu_98_bias_tile_5_we1;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_5_d1;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_6_address0;
wire    grp_load_output_bias32_fu_98_bias_tile_6_ce0;
wire    grp_load_output_bias32_fu_98_bias_tile_6_we0;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_6_d0;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_6_address1;
wire    grp_load_output_bias32_fu_98_bias_tile_6_ce1;
wire    grp_load_output_bias32_fu_98_bias_tile_6_we1;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_6_d1;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_7_address0;
wire    grp_load_output_bias32_fu_98_bias_tile_7_ce0;
wire    grp_load_output_bias32_fu_98_bias_tile_7_we0;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_7_d0;
wire   [1:0] grp_load_output_bias32_fu_98_bias_tile_7_address1;
wire    grp_load_output_bias32_fu_98_bias_tile_7_ce1;
wire    grp_load_output_bias32_fu_98_bias_tile_7_we1;
wire   [31:0] grp_load_output_bias32_fu_98_bias_tile_7_d1;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_start;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_done;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_idle;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_ready;
wire   [1:0] grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_address0;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_ce0;
wire   [13:0] grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_projected_address1;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_projected_ce1;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_projected_we1;
wire   [255:0] grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_projected_d1;
wire   [1:0] grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_1_address0;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_1_ce0;
wire   [1:0] grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_2_address0;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_2_ce0;
wire   [1:0] grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_3_address0;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_3_ce0;
wire   [1:0] grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_4_address0;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_4_ce0;
wire   [1:0] grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_5_address0;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_5_ce0;
wire   [1:0] grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_6_address0;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_6_ce0;
wire   [1:0] grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_7_address0;
wire    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_7_ce0;
reg    grp_load_output_bias32_fu_98_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [4:0] tile_fu_56;
wire   [4:0] add_ln79_fu_143_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_load_output_bias32_fu_98_ap_start_reg = 1'b0;
#0 grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_start_reg = 1'b0;
end

bert_attn_out_norm_residual_kernel_initialize_projection_bias_tile_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
bias_tile_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bias_tile_address0),
    .ce0(bias_tile_ce0),
    .we0(bias_tile_we0),
    .d0(grp_load_output_bias32_fu_98_bias_tile_0_d0),
    .q0(bias_tile_q0),
    .address1(grp_load_output_bias32_fu_98_bias_tile_0_address1),
    .ce1(bias_tile_ce1),
    .we1(bias_tile_we1),
    .d1(grp_load_output_bias32_fu_98_bias_tile_0_d1)
);

bert_attn_out_norm_residual_kernel_initialize_projection_bias_tile_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
bias_tile_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bias_tile_1_address0),
    .ce0(bias_tile_1_ce0),
    .we0(bias_tile_1_we0),
    .d0(grp_load_output_bias32_fu_98_bias_tile_1_d0),
    .q0(bias_tile_1_q0),
    .address1(grp_load_output_bias32_fu_98_bias_tile_1_address1),
    .ce1(bias_tile_1_ce1),
    .we1(bias_tile_1_we1),
    .d1(grp_load_output_bias32_fu_98_bias_tile_1_d1)
);

bert_attn_out_norm_residual_kernel_initialize_projection_bias_tile_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
bias_tile_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bias_tile_2_address0),
    .ce0(bias_tile_2_ce0),
    .we0(bias_tile_2_we0),
    .d0(grp_load_output_bias32_fu_98_bias_tile_2_d0),
    .q0(bias_tile_2_q0),
    .address1(grp_load_output_bias32_fu_98_bias_tile_2_address1),
    .ce1(bias_tile_2_ce1),
    .we1(bias_tile_2_we1),
    .d1(grp_load_output_bias32_fu_98_bias_tile_2_d1)
);

bert_attn_out_norm_residual_kernel_initialize_projection_bias_tile_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
bias_tile_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bias_tile_3_address0),
    .ce0(bias_tile_3_ce0),
    .we0(bias_tile_3_we0),
    .d0(grp_load_output_bias32_fu_98_bias_tile_3_d0),
    .q0(bias_tile_3_q0),
    .address1(grp_load_output_bias32_fu_98_bias_tile_3_address1),
    .ce1(bias_tile_3_ce1),
    .we1(bias_tile_3_we1),
    .d1(grp_load_output_bias32_fu_98_bias_tile_3_d1)
);

bert_attn_out_norm_residual_kernel_initialize_projection_bias_tile_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
bias_tile_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bias_tile_4_address0),
    .ce0(bias_tile_4_ce0),
    .we0(bias_tile_4_we0),
    .d0(grp_load_output_bias32_fu_98_bias_tile_4_d0),
    .q0(bias_tile_4_q0),
    .address1(grp_load_output_bias32_fu_98_bias_tile_4_address1),
    .ce1(bias_tile_4_ce1),
    .we1(bias_tile_4_we1),
    .d1(grp_load_output_bias32_fu_98_bias_tile_4_d1)
);

bert_attn_out_norm_residual_kernel_initialize_projection_bias_tile_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
bias_tile_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bias_tile_5_address0),
    .ce0(bias_tile_5_ce0),
    .we0(bias_tile_5_we0),
    .d0(grp_load_output_bias32_fu_98_bias_tile_5_d0),
    .q0(bias_tile_5_q0),
    .address1(grp_load_output_bias32_fu_98_bias_tile_5_address1),
    .ce1(bias_tile_5_ce1),
    .we1(bias_tile_5_we1),
    .d1(grp_load_output_bias32_fu_98_bias_tile_5_d1)
);

bert_attn_out_norm_residual_kernel_initialize_projection_bias_tile_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
bias_tile_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bias_tile_6_address0),
    .ce0(bias_tile_6_ce0),
    .we0(bias_tile_6_we0),
    .d0(grp_load_output_bias32_fu_98_bias_tile_6_d0),
    .q0(bias_tile_6_q0),
    .address1(grp_load_output_bias32_fu_98_bias_tile_6_address1),
    .ce1(bias_tile_6_ce1),
    .we1(bias_tile_6_we1),
    .d1(grp_load_output_bias32_fu_98_bias_tile_6_d1)
);

bert_attn_out_norm_residual_kernel_initialize_projection_bias_tile_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
bias_tile_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bias_tile_7_address0),
    .ce0(bias_tile_7_ce0),
    .we0(bias_tile_7_we0),
    .d0(grp_load_output_bias32_fu_98_bias_tile_7_d0),
    .q0(bias_tile_7_q0),
    .address1(grp_load_output_bias32_fu_98_bias_tile_7_address1),
    .ce1(bias_tile_7_ce1),
    .we1(bias_tile_7_we1),
    .d1(grp_load_output_bias32_fu_98_bias_tile_7_d1)
);

bert_attn_out_norm_residual_kernel_load_output_bias32 grp_load_output_bias32_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_output_bias32_fu_98_ap_start),
    .ap_done(grp_load_output_bias32_fu_98_ap_done),
    .ap_idle(grp_load_output_bias32_fu_98_ap_idle),
    .ap_ready(grp_load_output_bias32_fu_98_ap_ready),
    .m_axi_gmem_o_AWVALID(grp_load_output_bias32_fu_98_m_axi_gmem_o_AWVALID),
    .m_axi_gmem_o_AWREADY(1'b0),
    .m_axi_gmem_o_AWADDR(grp_load_output_bias32_fu_98_m_axi_gmem_o_AWADDR),
    .m_axi_gmem_o_AWID(grp_load_output_bias32_fu_98_m_axi_gmem_o_AWID),
    .m_axi_gmem_o_AWLEN(grp_load_output_bias32_fu_98_m_axi_gmem_o_AWLEN),
    .m_axi_gmem_o_AWSIZE(grp_load_output_bias32_fu_98_m_axi_gmem_o_AWSIZE),
    .m_axi_gmem_o_AWBURST(grp_load_output_bias32_fu_98_m_axi_gmem_o_AWBURST),
    .m_axi_gmem_o_AWLOCK(grp_load_output_bias32_fu_98_m_axi_gmem_o_AWLOCK),
    .m_axi_gmem_o_AWCACHE(grp_load_output_bias32_fu_98_m_axi_gmem_o_AWCACHE),
    .m_axi_gmem_o_AWPROT(grp_load_output_bias32_fu_98_m_axi_gmem_o_AWPROT),
    .m_axi_gmem_o_AWQOS(grp_load_output_bias32_fu_98_m_axi_gmem_o_AWQOS),
    .m_axi_gmem_o_AWREGION(grp_load_output_bias32_fu_98_m_axi_gmem_o_AWREGION),
    .m_axi_gmem_o_AWUSER(grp_load_output_bias32_fu_98_m_axi_gmem_o_AWUSER),
    .m_axi_gmem_o_WVALID(grp_load_output_bias32_fu_98_m_axi_gmem_o_WVALID),
    .m_axi_gmem_o_WREADY(1'b0),
    .m_axi_gmem_o_WDATA(grp_load_output_bias32_fu_98_m_axi_gmem_o_WDATA),
    .m_axi_gmem_o_WSTRB(grp_load_output_bias32_fu_98_m_axi_gmem_o_WSTRB),
    .m_axi_gmem_o_WLAST(grp_load_output_bias32_fu_98_m_axi_gmem_o_WLAST),
    .m_axi_gmem_o_WID(grp_load_output_bias32_fu_98_m_axi_gmem_o_WID),
    .m_axi_gmem_o_WUSER(grp_load_output_bias32_fu_98_m_axi_gmem_o_WUSER),
    .m_axi_gmem_o_ARVALID(grp_load_output_bias32_fu_98_m_axi_gmem_o_ARVALID),
    .m_axi_gmem_o_ARREADY(m_axi_gmem_o_ARREADY),
    .m_axi_gmem_o_ARADDR(grp_load_output_bias32_fu_98_m_axi_gmem_o_ARADDR),
    .m_axi_gmem_o_ARID(grp_load_output_bias32_fu_98_m_axi_gmem_o_ARID),
    .m_axi_gmem_o_ARLEN(grp_load_output_bias32_fu_98_m_axi_gmem_o_ARLEN),
    .m_axi_gmem_o_ARSIZE(grp_load_output_bias32_fu_98_m_axi_gmem_o_ARSIZE),
    .m_axi_gmem_o_ARBURST(grp_load_output_bias32_fu_98_m_axi_gmem_o_ARBURST),
    .m_axi_gmem_o_ARLOCK(grp_load_output_bias32_fu_98_m_axi_gmem_o_ARLOCK),
    .m_axi_gmem_o_ARCACHE(grp_load_output_bias32_fu_98_m_axi_gmem_o_ARCACHE),
    .m_axi_gmem_o_ARPROT(grp_load_output_bias32_fu_98_m_axi_gmem_o_ARPROT),
    .m_axi_gmem_o_ARQOS(grp_load_output_bias32_fu_98_m_axi_gmem_o_ARQOS),
    .m_axi_gmem_o_ARREGION(grp_load_output_bias32_fu_98_m_axi_gmem_o_ARREGION),
    .m_axi_gmem_o_ARUSER(grp_load_output_bias32_fu_98_m_axi_gmem_o_ARUSER),
    .m_axi_gmem_o_RVALID(m_axi_gmem_o_RVALID),
    .m_axi_gmem_o_RREADY(grp_load_output_bias32_fu_98_m_axi_gmem_o_RREADY),
    .m_axi_gmem_o_RDATA(m_axi_gmem_o_RDATA),
    .m_axi_gmem_o_RLAST(m_axi_gmem_o_RLAST),
    .m_axi_gmem_o_RID(m_axi_gmem_o_RID),
    .m_axi_gmem_o_RFIFONUM(m_axi_gmem_o_RFIFONUM),
    .m_axi_gmem_o_RUSER(m_axi_gmem_o_RUSER),
    .m_axi_gmem_o_RRESP(m_axi_gmem_o_RRESP),
    .m_axi_gmem_o_BVALID(1'b0),
    .m_axi_gmem_o_BREADY(grp_load_output_bias32_fu_98_m_axi_gmem_o_BREADY),
    .m_axi_gmem_o_BRESP(2'd0),
    .m_axi_gmem_o_BID(1'd0),
    .m_axi_gmem_o_BUSER(1'd0),
    .bias(bias),
    .out_base(shl_ln_reg_183),
    .bias_tile_0_address0(grp_load_output_bias32_fu_98_bias_tile_0_address0),
    .bias_tile_0_ce0(grp_load_output_bias32_fu_98_bias_tile_0_ce0),
    .bias_tile_0_we0(grp_load_output_bias32_fu_98_bias_tile_0_we0),
    .bias_tile_0_d0(grp_load_output_bias32_fu_98_bias_tile_0_d0),
    .bias_tile_0_address1(grp_load_output_bias32_fu_98_bias_tile_0_address1),
    .bias_tile_0_ce1(grp_load_output_bias32_fu_98_bias_tile_0_ce1),
    .bias_tile_0_we1(grp_load_output_bias32_fu_98_bias_tile_0_we1),
    .bias_tile_0_d1(grp_load_output_bias32_fu_98_bias_tile_0_d1),
    .bias_tile_1_address0(grp_load_output_bias32_fu_98_bias_tile_1_address0),
    .bias_tile_1_ce0(grp_load_output_bias32_fu_98_bias_tile_1_ce0),
    .bias_tile_1_we0(grp_load_output_bias32_fu_98_bias_tile_1_we0),
    .bias_tile_1_d0(grp_load_output_bias32_fu_98_bias_tile_1_d0),
    .bias_tile_1_address1(grp_load_output_bias32_fu_98_bias_tile_1_address1),
    .bias_tile_1_ce1(grp_load_output_bias32_fu_98_bias_tile_1_ce1),
    .bias_tile_1_we1(grp_load_output_bias32_fu_98_bias_tile_1_we1),
    .bias_tile_1_d1(grp_load_output_bias32_fu_98_bias_tile_1_d1),
    .bias_tile_2_address0(grp_load_output_bias32_fu_98_bias_tile_2_address0),
    .bias_tile_2_ce0(grp_load_output_bias32_fu_98_bias_tile_2_ce0),
    .bias_tile_2_we0(grp_load_output_bias32_fu_98_bias_tile_2_we0),
    .bias_tile_2_d0(grp_load_output_bias32_fu_98_bias_tile_2_d0),
    .bias_tile_2_address1(grp_load_output_bias32_fu_98_bias_tile_2_address1),
    .bias_tile_2_ce1(grp_load_output_bias32_fu_98_bias_tile_2_ce1),
    .bias_tile_2_we1(grp_load_output_bias32_fu_98_bias_tile_2_we1),
    .bias_tile_2_d1(grp_load_output_bias32_fu_98_bias_tile_2_d1),
    .bias_tile_3_address0(grp_load_output_bias32_fu_98_bias_tile_3_address0),
    .bias_tile_3_ce0(grp_load_output_bias32_fu_98_bias_tile_3_ce0),
    .bias_tile_3_we0(grp_load_output_bias32_fu_98_bias_tile_3_we0),
    .bias_tile_3_d0(grp_load_output_bias32_fu_98_bias_tile_3_d0),
    .bias_tile_3_address1(grp_load_output_bias32_fu_98_bias_tile_3_address1),
    .bias_tile_3_ce1(grp_load_output_bias32_fu_98_bias_tile_3_ce1),
    .bias_tile_3_we1(grp_load_output_bias32_fu_98_bias_tile_3_we1),
    .bias_tile_3_d1(grp_load_output_bias32_fu_98_bias_tile_3_d1),
    .bias_tile_4_address0(grp_load_output_bias32_fu_98_bias_tile_4_address0),
    .bias_tile_4_ce0(grp_load_output_bias32_fu_98_bias_tile_4_ce0),
    .bias_tile_4_we0(grp_load_output_bias32_fu_98_bias_tile_4_we0),
    .bias_tile_4_d0(grp_load_output_bias32_fu_98_bias_tile_4_d0),
    .bias_tile_4_address1(grp_load_output_bias32_fu_98_bias_tile_4_address1),
    .bias_tile_4_ce1(grp_load_output_bias32_fu_98_bias_tile_4_ce1),
    .bias_tile_4_we1(grp_load_output_bias32_fu_98_bias_tile_4_we1),
    .bias_tile_4_d1(grp_load_output_bias32_fu_98_bias_tile_4_d1),
    .bias_tile_5_address0(grp_load_output_bias32_fu_98_bias_tile_5_address0),
    .bias_tile_5_ce0(grp_load_output_bias32_fu_98_bias_tile_5_ce0),
    .bias_tile_5_we0(grp_load_output_bias32_fu_98_bias_tile_5_we0),
    .bias_tile_5_d0(grp_load_output_bias32_fu_98_bias_tile_5_d0),
    .bias_tile_5_address1(grp_load_output_bias32_fu_98_bias_tile_5_address1),
    .bias_tile_5_ce1(grp_load_output_bias32_fu_98_bias_tile_5_ce1),
    .bias_tile_5_we1(grp_load_output_bias32_fu_98_bias_tile_5_we1),
    .bias_tile_5_d1(grp_load_output_bias32_fu_98_bias_tile_5_d1),
    .bias_tile_6_address0(grp_load_output_bias32_fu_98_bias_tile_6_address0),
    .bias_tile_6_ce0(grp_load_output_bias32_fu_98_bias_tile_6_ce0),
    .bias_tile_6_we0(grp_load_output_bias32_fu_98_bias_tile_6_we0),
    .bias_tile_6_d0(grp_load_output_bias32_fu_98_bias_tile_6_d0),
    .bias_tile_6_address1(grp_load_output_bias32_fu_98_bias_tile_6_address1),
    .bias_tile_6_ce1(grp_load_output_bias32_fu_98_bias_tile_6_ce1),
    .bias_tile_6_we1(grp_load_output_bias32_fu_98_bias_tile_6_we1),
    .bias_tile_6_d1(grp_load_output_bias32_fu_98_bias_tile_6_d1),
    .bias_tile_7_address0(grp_load_output_bias32_fu_98_bias_tile_7_address0),
    .bias_tile_7_ce0(grp_load_output_bias32_fu_98_bias_tile_7_ce0),
    .bias_tile_7_we0(grp_load_output_bias32_fu_98_bias_tile_7_we0),
    .bias_tile_7_d0(grp_load_output_bias32_fu_98_bias_tile_7_d0),
    .bias_tile_7_address1(grp_load_output_bias32_fu_98_bias_tile_7_address1),
    .bias_tile_7_ce1(grp_load_output_bias32_fu_98_bias_tile_7_ce1),
    .bias_tile_7_we1(grp_load_output_bias32_fu_98_bias_tile_7_we1),
    .bias_tile_7_d1(grp_load_output_bias32_fu_98_bias_tile_7_d1)
);

bert_attn_out_norm_residual_kernel_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_start),
    .ap_done(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_done),
    .ap_idle(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_idle),
    .ap_ready(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_ready),
    .bias_tile_address0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_address0),
    .bias_tile_ce0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_ce0),
    .bias_tile_q0(bias_tile_q0),
    .tile(tile_1_reg_175),
    .projected_address1(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_projected_address1),
    .projected_ce1(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_projected_ce1),
    .projected_we1(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_projected_we1),
    .projected_d1(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_projected_d1),
    .bias_tile_1_address0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_1_address0),
    .bias_tile_1_ce0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_1_ce0),
    .bias_tile_1_q0(bias_tile_1_q0),
    .bias_tile_2_address0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_2_address0),
    .bias_tile_2_ce0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_2_ce0),
    .bias_tile_2_q0(bias_tile_2_q0),
    .bias_tile_3_address0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_3_address0),
    .bias_tile_3_ce0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_3_ce0),
    .bias_tile_3_q0(bias_tile_3_q0),
    .bias_tile_4_address0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_4_address0),
    .bias_tile_4_ce0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_4_ce0),
    .bias_tile_4_q0(bias_tile_4_q0),
    .bias_tile_5_address0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_5_address0),
    .bias_tile_5_ce0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_5_ce0),
    .bias_tile_5_q0(bias_tile_5_q0),
    .bias_tile_6_address0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_6_address0),
    .bias_tile_6_ce0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_6_ce0),
    .bias_tile_6_q0(bias_tile_6_q0),
    .bias_tile_7_address0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_7_address0),
    .bias_tile_7_ce0(grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_7_ce0),
    .bias_tile_7_q0(bias_tile_7_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_start_reg <= 1'b1;
        end else if ((grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_ready == 1'b1)) begin
            grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_output_bias32_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln79_fu_137_p2 == 1'd0))) begin
            grp_load_output_bias32_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_load_output_bias32_fu_98_ap_ready == 1'b1)) begin
            grp_load_output_bias32_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tile_fu_56 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln79_fu_137_p2 == 1'd0))) begin
        tile_fu_56 <= add_ln79_fu_143_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln79_fu_137_p2 == 1'd0))) begin
        shl_ln_reg_183[9 : 5] <= shl_ln_fu_149_p3[9 : 5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_1_reg_175 <= tile_fu_56;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_load_output_bias32_fu_98_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (icmp_ln79_fu_137_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln79_fu_137_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_1_address0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_1_address0 = grp_load_output_bias32_fu_98_bias_tile_1_address0;
    end else begin
        bias_tile_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_1_ce0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_1_ce0 = grp_load_output_bias32_fu_98_bias_tile_1_ce0;
    end else begin
        bias_tile_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_1_ce1 = grp_load_output_bias32_fu_98_bias_tile_1_ce1;
    end else begin
        bias_tile_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_1_we0 = grp_load_output_bias32_fu_98_bias_tile_1_we0;
    end else begin
        bias_tile_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_1_we1 = grp_load_output_bias32_fu_98_bias_tile_1_we1;
    end else begin
        bias_tile_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_2_address0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_2_address0 = grp_load_output_bias32_fu_98_bias_tile_2_address0;
    end else begin
        bias_tile_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_2_ce0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_2_ce0 = grp_load_output_bias32_fu_98_bias_tile_2_ce0;
    end else begin
        bias_tile_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_2_ce1 = grp_load_output_bias32_fu_98_bias_tile_2_ce1;
    end else begin
        bias_tile_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_2_we0 = grp_load_output_bias32_fu_98_bias_tile_2_we0;
    end else begin
        bias_tile_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_2_we1 = grp_load_output_bias32_fu_98_bias_tile_2_we1;
    end else begin
        bias_tile_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_3_address0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_3_address0 = grp_load_output_bias32_fu_98_bias_tile_3_address0;
    end else begin
        bias_tile_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_3_ce0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_3_ce0 = grp_load_output_bias32_fu_98_bias_tile_3_ce0;
    end else begin
        bias_tile_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_3_ce1 = grp_load_output_bias32_fu_98_bias_tile_3_ce1;
    end else begin
        bias_tile_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_3_we0 = grp_load_output_bias32_fu_98_bias_tile_3_we0;
    end else begin
        bias_tile_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_3_we1 = grp_load_output_bias32_fu_98_bias_tile_3_we1;
    end else begin
        bias_tile_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_4_address0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_4_address0 = grp_load_output_bias32_fu_98_bias_tile_4_address0;
    end else begin
        bias_tile_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_4_ce0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_4_ce0 = grp_load_output_bias32_fu_98_bias_tile_4_ce0;
    end else begin
        bias_tile_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_4_ce1 = grp_load_output_bias32_fu_98_bias_tile_4_ce1;
    end else begin
        bias_tile_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_4_we0 = grp_load_output_bias32_fu_98_bias_tile_4_we0;
    end else begin
        bias_tile_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_4_we1 = grp_load_output_bias32_fu_98_bias_tile_4_we1;
    end else begin
        bias_tile_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_5_address0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_5_address0 = grp_load_output_bias32_fu_98_bias_tile_5_address0;
    end else begin
        bias_tile_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_5_ce0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_5_ce0 = grp_load_output_bias32_fu_98_bias_tile_5_ce0;
    end else begin
        bias_tile_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_5_ce1 = grp_load_output_bias32_fu_98_bias_tile_5_ce1;
    end else begin
        bias_tile_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_5_we0 = grp_load_output_bias32_fu_98_bias_tile_5_we0;
    end else begin
        bias_tile_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_5_we1 = grp_load_output_bias32_fu_98_bias_tile_5_we1;
    end else begin
        bias_tile_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_6_address0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_6_address0 = grp_load_output_bias32_fu_98_bias_tile_6_address0;
    end else begin
        bias_tile_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_6_ce0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_6_ce0 = grp_load_output_bias32_fu_98_bias_tile_6_ce0;
    end else begin
        bias_tile_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_6_ce1 = grp_load_output_bias32_fu_98_bias_tile_6_ce1;
    end else begin
        bias_tile_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_6_we0 = grp_load_output_bias32_fu_98_bias_tile_6_we0;
    end else begin
        bias_tile_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_6_we1 = grp_load_output_bias32_fu_98_bias_tile_6_we1;
    end else begin
        bias_tile_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_7_address0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_7_address0 = grp_load_output_bias32_fu_98_bias_tile_7_address0;
    end else begin
        bias_tile_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_7_ce0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_7_ce0 = grp_load_output_bias32_fu_98_bias_tile_7_ce0;
    end else begin
        bias_tile_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_7_ce1 = grp_load_output_bias32_fu_98_bias_tile_7_ce1;
    end else begin
        bias_tile_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_7_we0 = grp_load_output_bias32_fu_98_bias_tile_7_we0;
    end else begin
        bias_tile_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_7_we1 = grp_load_output_bias32_fu_98_bias_tile_7_we1;
    end else begin
        bias_tile_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_address0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_address0 = grp_load_output_bias32_fu_98_bias_tile_0_address0;
    end else begin
        bias_tile_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bias_tile_ce0 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_bias_tile_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_ce0 = grp_load_output_bias32_fu_98_bias_tile_0_ce0;
    end else begin
        bias_tile_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_ce1 = grp_load_output_bias32_fu_98_bias_tile_0_ce1;
    end else begin
        bias_tile_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_we0 = grp_load_output_bias32_fu_98_bias_tile_0_we0;
    end else begin
        bias_tile_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bias_tile_we1 = grp_load_output_bias32_fu_98_bias_tile_0_we1;
    end else begin
        bias_tile_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln79_fu_137_p2 == 1'd0)))) begin
        m_axi_gmem_o_ARVALID = grp_load_output_bias32_fu_98_m_axi_gmem_o_ARVALID;
    end else begin
        m_axi_gmem_o_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln79_fu_137_p2 == 1'd0)))) begin
        m_axi_gmem_o_RREADY = grp_load_output_bias32_fu_98_m_axi_gmem_o_RREADY;
    end else begin
        m_axi_gmem_o_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln79_fu_137_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_load_output_bias32_fu_98_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln79_fu_143_p2 = (tile_fu_56 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_start = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_ap_start_reg;

assign grp_load_output_bias32_fu_98_ap_start = grp_load_output_bias32_fu_98_ap_start_reg;

assign icmp_ln79_fu_137_p2 = ((tile_fu_56 == 5'd24) ? 1'b1 : 1'b0);

assign m_axi_gmem_o_ARADDR = grp_load_output_bias32_fu_98_m_axi_gmem_o_ARADDR;

assign m_axi_gmem_o_ARBURST = grp_load_output_bias32_fu_98_m_axi_gmem_o_ARBURST;

assign m_axi_gmem_o_ARCACHE = grp_load_output_bias32_fu_98_m_axi_gmem_o_ARCACHE;

assign m_axi_gmem_o_ARID = grp_load_output_bias32_fu_98_m_axi_gmem_o_ARID;

assign m_axi_gmem_o_ARLEN = grp_load_output_bias32_fu_98_m_axi_gmem_o_ARLEN;

assign m_axi_gmem_o_ARLOCK = grp_load_output_bias32_fu_98_m_axi_gmem_o_ARLOCK;

assign m_axi_gmem_o_ARPROT = grp_load_output_bias32_fu_98_m_axi_gmem_o_ARPROT;

assign m_axi_gmem_o_ARQOS = grp_load_output_bias32_fu_98_m_axi_gmem_o_ARQOS;

assign m_axi_gmem_o_ARREGION = grp_load_output_bias32_fu_98_m_axi_gmem_o_ARREGION;

assign m_axi_gmem_o_ARSIZE = grp_load_output_bias32_fu_98_m_axi_gmem_o_ARSIZE;

assign m_axi_gmem_o_ARUSER = grp_load_output_bias32_fu_98_m_axi_gmem_o_ARUSER;

assign m_axi_gmem_o_AWADDR = 64'd0;

assign m_axi_gmem_o_AWBURST = 2'd0;

assign m_axi_gmem_o_AWCACHE = 4'd0;

assign m_axi_gmem_o_AWID = 1'd0;

assign m_axi_gmem_o_AWLEN = 32'd0;

assign m_axi_gmem_o_AWLOCK = 2'd0;

assign m_axi_gmem_o_AWPROT = 3'd0;

assign m_axi_gmem_o_AWQOS = 4'd0;

assign m_axi_gmem_o_AWREGION = 4'd0;

assign m_axi_gmem_o_AWSIZE = 3'd0;

assign m_axi_gmem_o_AWUSER = 1'd0;

assign m_axi_gmem_o_AWVALID = 1'b0;

assign m_axi_gmem_o_BREADY = 1'b0;

assign m_axi_gmem_o_WDATA = 512'd0;

assign m_axi_gmem_o_WID = 1'd0;

assign m_axi_gmem_o_WLAST = 1'b0;

assign m_axi_gmem_o_WSTRB = 64'd0;

assign m_axi_gmem_o_WUSER = 1'd0;

assign m_axi_gmem_o_WVALID = 1'b0;

assign projected_address1 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_projected_address1;

assign projected_ce1 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_projected_ce1;

assign projected_d1 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_projected_d1;

assign projected_we1 = grp_initialize_projection_Pipeline_INIT_PROJECTION_ROW_INIT_PROJECTION_OUT_fu_114_projected_we1;

assign shl_ln_fu_149_p3 = {{tile_fu_56}, {5'd0}};

always @ (posedge ap_clk) begin
    shl_ln_reg_183[4:0] <= 5'b00000;
end

endmodule //bert_attn_out_norm_residual_kernel_initialize_projection
