// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bert_attn_out_norm_residual_kernel_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_hidden_AWVALID,
        m_axi_gmem_hidden_AWREADY,
        m_axi_gmem_hidden_AWADDR,
        m_axi_gmem_hidden_AWID,
        m_axi_gmem_hidden_AWLEN,
        m_axi_gmem_hidden_AWSIZE,
        m_axi_gmem_hidden_AWBURST,
        m_axi_gmem_hidden_AWLOCK,
        m_axi_gmem_hidden_AWCACHE,
        m_axi_gmem_hidden_AWPROT,
        m_axi_gmem_hidden_AWQOS,
        m_axi_gmem_hidden_AWREGION,
        m_axi_gmem_hidden_AWUSER,
        m_axi_gmem_hidden_WVALID,
        m_axi_gmem_hidden_WREADY,
        m_axi_gmem_hidden_WDATA,
        m_axi_gmem_hidden_WSTRB,
        m_axi_gmem_hidden_WLAST,
        m_axi_gmem_hidden_WID,
        m_axi_gmem_hidden_WUSER,
        m_axi_gmem_hidden_ARVALID,
        m_axi_gmem_hidden_ARREADY,
        m_axi_gmem_hidden_ARADDR,
        m_axi_gmem_hidden_ARID,
        m_axi_gmem_hidden_ARLEN,
        m_axi_gmem_hidden_ARSIZE,
        m_axi_gmem_hidden_ARBURST,
        m_axi_gmem_hidden_ARLOCK,
        m_axi_gmem_hidden_ARCACHE,
        m_axi_gmem_hidden_ARPROT,
        m_axi_gmem_hidden_ARQOS,
        m_axi_gmem_hidden_ARREGION,
        m_axi_gmem_hidden_ARUSER,
        m_axi_gmem_hidden_RVALID,
        m_axi_gmem_hidden_RREADY,
        m_axi_gmem_hidden_RDATA,
        m_axi_gmem_hidden_RLAST,
        m_axi_gmem_hidden_RID,
        m_axi_gmem_hidden_RFIFONUM,
        m_axi_gmem_hidden_RUSER,
        m_axi_gmem_hidden_RRESP,
        m_axi_gmem_hidden_BVALID,
        m_axi_gmem_hidden_BREADY,
        m_axi_gmem_hidden_BRESP,
        m_axi_gmem_hidden_BID,
        m_axi_gmem_hidden_BUSER,
        sext_ln11,
        residual_address1,
        residual_ce1,
        residual_we1,
        residual_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_hidden_AWVALID;
input   m_axi_gmem_hidden_AWREADY;
output  [63:0] m_axi_gmem_hidden_AWADDR;
output  [0:0] m_axi_gmem_hidden_AWID;
output  [31:0] m_axi_gmem_hidden_AWLEN;
output  [2:0] m_axi_gmem_hidden_AWSIZE;
output  [1:0] m_axi_gmem_hidden_AWBURST;
output  [1:0] m_axi_gmem_hidden_AWLOCK;
output  [3:0] m_axi_gmem_hidden_AWCACHE;
output  [2:0] m_axi_gmem_hidden_AWPROT;
output  [3:0] m_axi_gmem_hidden_AWQOS;
output  [3:0] m_axi_gmem_hidden_AWREGION;
output  [0:0] m_axi_gmem_hidden_AWUSER;
output   m_axi_gmem_hidden_WVALID;
input   m_axi_gmem_hidden_WREADY;
output  [511:0] m_axi_gmem_hidden_WDATA;
output  [63:0] m_axi_gmem_hidden_WSTRB;
output   m_axi_gmem_hidden_WLAST;
output  [0:0] m_axi_gmem_hidden_WID;
output  [0:0] m_axi_gmem_hidden_WUSER;
output   m_axi_gmem_hidden_ARVALID;
input   m_axi_gmem_hidden_ARREADY;
output  [63:0] m_axi_gmem_hidden_ARADDR;
output  [0:0] m_axi_gmem_hidden_ARID;
output  [31:0] m_axi_gmem_hidden_ARLEN;
output  [2:0] m_axi_gmem_hidden_ARSIZE;
output  [1:0] m_axi_gmem_hidden_ARBURST;
output  [1:0] m_axi_gmem_hidden_ARLOCK;
output  [3:0] m_axi_gmem_hidden_ARCACHE;
output  [2:0] m_axi_gmem_hidden_ARPROT;
output  [3:0] m_axi_gmem_hidden_ARQOS;
output  [3:0] m_axi_gmem_hidden_ARREGION;
output  [0:0] m_axi_gmem_hidden_ARUSER;
input   m_axi_gmem_hidden_RVALID;
output   m_axi_gmem_hidden_RREADY;
input  [511:0] m_axi_gmem_hidden_RDATA;
input   m_axi_gmem_hidden_RLAST;
input  [0:0] m_axi_gmem_hidden_RID;
input  [8:0] m_axi_gmem_hidden_RFIFONUM;
input  [0:0] m_axi_gmem_hidden_RUSER;
input  [1:0] m_axi_gmem_hidden_RRESP;
input   m_axi_gmem_hidden_BVALID;
output   m_axi_gmem_hidden_BREADY;
input  [1:0] m_axi_gmem_hidden_BRESP;
input  [0:0] m_axi_gmem_hidden_BID;
input  [0:0] m_axi_gmem_hidden_BUSER;
input  [57:0] sext_ln11;
output  [12:0] residual_address1;
output   residual_ce1;
output   residual_we1;
output  [511:0] residual_d1;

reg ap_idle;
reg m_axi_gmem_hidden_RREADY;
reg residual_ce1;
reg residual_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln11_reg_279;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln11_fu_136_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_hidden_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [12:0] add_ln21_fu_227_p2;
reg   [12:0] add_ln21_reg_283;
reg   [511:0] t_reg_288;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln21_2_fu_249_p1;
reg   [5:0] p_fu_74;
wire   [5:0] add_ln13_fu_233_p2;
wire    ap_loop_init;
reg   [7:0] s_fu_78;
wire   [7:0] select_ln11_1_fu_185_p3;
reg   [12:0] indvar_flatten_fu_82;
wire   [12:0] add_ln11_1_fu_142_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [0:0] icmp_ln13_fu_171_p2;
wire   [7:0] add_ln11_fu_165_p2;
wire   [6:0] trunc_ln21_fu_193_p1;
wire   [11:0] tmp_s_fu_205_p3;
wire   [12:0] tmp_fu_197_p3;
wire   [12:0] zext_ln21_fu_213_p1;
wire   [5:0] select_ln11_fu_177_p3;
wire   [12:0] sub_ln21_fu_217_p2;
wire   [12:0] zext_ln21_1_fu_223_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

bert_attn_out_norm_residual_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln11_fu_136_p2 == 1'd0))) begin
            indvar_flatten_fu_82 <= add_ln11_1_fu_142_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_82 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_fu_74 <= 6'd0;
        end else if (((icmp_ln11_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_fu_74 <= add_ln13_fu_233_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            s_fu_78 <= 8'd0;
        end else if (((icmp_ln11_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            s_fu_78 <= select_ln11_1_fu_185_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln11_reg_279 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln21_reg_283 <= add_ln21_fu_227_p2;
        t_reg_288 <= m_axi_gmem_hidden_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln11_reg_279 <= icmp_ln11_fu_136_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln11_fu_136_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln11_reg_279 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln11_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem_hidden_blk_n_R = m_axi_gmem_hidden_RVALID;
    end else begin
        gmem_hidden_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln11_reg_279 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem_hidden_RREADY = 1'b1;
    end else begin
        m_axi_gmem_hidden_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        residual_ce1 = 1'b1;
    end else begin
        residual_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        residual_we1 = 1'b1;
    end else begin
        residual_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln11_1_fu_142_p2 = (ap_sig_allocacmp_indvar_flatten_load + 13'd1);

assign add_ln11_fu_165_p2 = (s_fu_78 + 8'd1);

assign add_ln13_fu_233_p2 = (select_ln11_fu_177_p3 + 6'd1);

assign add_ln21_fu_227_p2 = (sub_ln21_fu_217_p2 + zext_ln21_1_fu_223_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln11_reg_279 == 1'd0) & (m_axi_gmem_hidden_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln11_reg_279 == 1'd0) & (m_axi_gmem_hidden_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln11_reg_279 == 1'd0) & (m_axi_gmem_hidden_RVALID == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln11_fu_136_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 13'd6144) ? 1'b1 : 1'b0);

assign icmp_ln13_fu_171_p2 = ((p_fu_74 == 6'd48) ? 1'b1 : 1'b0);

assign m_axi_gmem_hidden_ARADDR = 64'd0;

assign m_axi_gmem_hidden_ARBURST = 2'd0;

assign m_axi_gmem_hidden_ARCACHE = 4'd0;

assign m_axi_gmem_hidden_ARID = 1'd0;

assign m_axi_gmem_hidden_ARLEN = 32'd0;

assign m_axi_gmem_hidden_ARLOCK = 2'd0;

assign m_axi_gmem_hidden_ARPROT = 3'd0;

assign m_axi_gmem_hidden_ARQOS = 4'd0;

assign m_axi_gmem_hidden_ARREGION = 4'd0;

assign m_axi_gmem_hidden_ARSIZE = 3'd0;

assign m_axi_gmem_hidden_ARUSER = 1'd0;

assign m_axi_gmem_hidden_ARVALID = 1'b0;

assign m_axi_gmem_hidden_AWADDR = 64'd0;

assign m_axi_gmem_hidden_AWBURST = 2'd0;

assign m_axi_gmem_hidden_AWCACHE = 4'd0;

assign m_axi_gmem_hidden_AWID = 1'd0;

assign m_axi_gmem_hidden_AWLEN = 32'd0;

assign m_axi_gmem_hidden_AWLOCK = 2'd0;

assign m_axi_gmem_hidden_AWPROT = 3'd0;

assign m_axi_gmem_hidden_AWQOS = 4'd0;

assign m_axi_gmem_hidden_AWREGION = 4'd0;

assign m_axi_gmem_hidden_AWSIZE = 3'd0;

assign m_axi_gmem_hidden_AWUSER = 1'd0;

assign m_axi_gmem_hidden_AWVALID = 1'b0;

assign m_axi_gmem_hidden_BREADY = 1'b0;

assign m_axi_gmem_hidden_WDATA = 512'd0;

assign m_axi_gmem_hidden_WID = 1'd0;

assign m_axi_gmem_hidden_WLAST = 1'b0;

assign m_axi_gmem_hidden_WSTRB = 64'd0;

assign m_axi_gmem_hidden_WUSER = 1'd0;

assign m_axi_gmem_hidden_WVALID = 1'b0;

assign residual_address1 = zext_ln21_2_fu_249_p1;

assign residual_d1 = t_reg_288;

assign select_ln11_1_fu_185_p3 = ((icmp_ln13_fu_171_p2[0:0] == 1'b1) ? add_ln11_fu_165_p2 : s_fu_78);

assign select_ln11_fu_177_p3 = ((icmp_ln13_fu_171_p2[0:0] == 1'b1) ? 6'd0 : p_fu_74);

assign sub_ln21_fu_217_p2 = (tmp_fu_197_p3 - zext_ln21_fu_213_p1);

assign tmp_fu_197_p3 = {{trunc_ln21_fu_193_p1}, {6'd0}};

assign tmp_s_fu_205_p3 = {{select_ln11_1_fu_185_p3}, {4'd0}};

assign trunc_ln21_fu_193_p1 = select_ln11_1_fu_185_p3[6:0];

assign zext_ln21_1_fu_223_p1 = select_ln11_fu_177_p3;

assign zext_ln21_2_fu_249_p1 = add_ln21_reg_283;

assign zext_ln21_fu_213_p1 = tmp_s_fu_205_p3;

endmodule //bert_attn_out_norm_residual_kernel_load_residual_Pipeline_LOAD_RESIDUAL_ROW_LOAD_RESIDUAL_PACK
