// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bert_attn_out_norm_residual_kernel_residual_norm_and_write_Pipeline_NORM_REDUCE_PACK (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sub_ln248,
        residual_address0,
        residual_ce0,
        residual_q0,
        sub_ln248_1,
        projected_address0,
        projected_ce0,
        projected_q0,
        projected_address1,
        projected_ce1,
        projected_q1,
        add32_1564_out,
        add32_1564_out_ap_vld,
        add28_1563_out,
        add28_1563_out_ap_vld,
        add32_1462_out,
        add32_1462_out_ap_vld,
        add28_1461_out,
        add28_1461_out_ap_vld,
        add32_1360_out,
        add32_1360_out_ap_vld,
        add28_1359_out,
        add28_1359_out_ap_vld,
        add32_1258_out,
        add32_1258_out_ap_vld,
        add28_1257_out,
        add28_1257_out_ap_vld,
        add32_1156_out,
        add32_1156_out_ap_vld,
        add28_1155_out,
        add28_1155_out_ap_vld,
        add32_1054_out,
        add32_1054_out_ap_vld,
        add28_1053_out,
        add28_1053_out_ap_vld,
        add32_952_out,
        add32_952_out_ap_vld,
        add28_951_out,
        add28_951_out_ap_vld,
        add32_850_out,
        add32_850_out_ap_vld,
        add28_849_out,
        add28_849_out_ap_vld,
        add32_748_out,
        add32_748_out_ap_vld,
        add28_747_out,
        add28_747_out_ap_vld,
        add32_646_out,
        add32_646_out_ap_vld,
        add28_645_out,
        add28_645_out_ap_vld,
        add32_544_out,
        add32_544_out_ap_vld,
        add28_543_out,
        add28_543_out_ap_vld,
        add32_442_out,
        add32_442_out_ap_vld,
        add28_441_out,
        add28_441_out_ap_vld,
        add32_340_out,
        add32_340_out_ap_vld,
        add28_339_out,
        add28_339_out_ap_vld,
        add32_238_out,
        add32_238_out_ap_vld,
        add28_237_out,
        add28_237_out_ap_vld,
        add32_136_out,
        add32_136_out_ap_vld,
        add28_135_out,
        add28_135_out_ap_vld,
        add3234_out,
        add3234_out_ap_vld,
        add2833_out,
        add2833_out_ap_vld,
        grp_fu_405_p_din0,
        grp_fu_405_p_din1,
        grp_fu_405_p_opcode,
        grp_fu_405_p_dout0,
        grp_fu_405_p_ce,
        grp_fu_1040_p_din0,
        grp_fu_1040_p_din1,
        grp_fu_1040_p_opcode,
        grp_fu_1040_p_dout0,
        grp_fu_1040_p_ce,
        grp_fu_1044_p_din0,
        grp_fu_1044_p_din1,
        grp_fu_1044_p_opcode,
        grp_fu_1044_p_dout0,
        grp_fu_1044_p_ce,
        grp_fu_1048_p_din0,
        grp_fu_1048_p_din1,
        grp_fu_1048_p_opcode,
        grp_fu_1048_p_dout0,
        grp_fu_1048_p_ce,
        grp_fu_410_p_din0,
        grp_fu_410_p_din1,
        grp_fu_410_p_dout0,
        grp_fu_410_p_ce,
        grp_fu_415_p_din0,
        grp_fu_415_p_din1,
        grp_fu_415_p_dout0,
        grp_fu_415_p_ce,
        grp_fu_1052_p_din0,
        grp_fu_1052_p_din1,
        grp_fu_1052_p_dout0,
        grp_fu_1052_p_ce,
        grp_fu_1056_p_din0,
        grp_fu_1056_p_din1,
        grp_fu_1056_p_dout0,
        grp_fu_1056_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [12:0] sub_ln248;
output  [12:0] residual_address0;
output   residual_ce0;
input  [511:0] residual_q0;
input  [13:0] sub_ln248_1;
output  [13:0] projected_address0;
output   projected_ce0;
input  [255:0] projected_q0;
output  [13:0] projected_address1;
output   projected_ce1;
input  [255:0] projected_q1;
output  [31:0] add32_1564_out;
output   add32_1564_out_ap_vld;
output  [31:0] add28_1563_out;
output   add28_1563_out_ap_vld;
output  [31:0] add32_1462_out;
output   add32_1462_out_ap_vld;
output  [31:0] add28_1461_out;
output   add28_1461_out_ap_vld;
output  [31:0] add32_1360_out;
output   add32_1360_out_ap_vld;
output  [31:0] add28_1359_out;
output   add28_1359_out_ap_vld;
output  [31:0] add32_1258_out;
output   add32_1258_out_ap_vld;
output  [31:0] add28_1257_out;
output   add28_1257_out_ap_vld;
output  [31:0] add32_1156_out;
output   add32_1156_out_ap_vld;
output  [31:0] add28_1155_out;
output   add28_1155_out_ap_vld;
output  [31:0] add32_1054_out;
output   add32_1054_out_ap_vld;
output  [31:0] add28_1053_out;
output   add28_1053_out_ap_vld;
output  [31:0] add32_952_out;
output   add32_952_out_ap_vld;
output  [31:0] add28_951_out;
output   add28_951_out_ap_vld;
output  [31:0] add32_850_out;
output   add32_850_out_ap_vld;
output  [31:0] add28_849_out;
output   add28_849_out_ap_vld;
output  [31:0] add32_748_out;
output   add32_748_out_ap_vld;
output  [31:0] add28_747_out;
output   add28_747_out_ap_vld;
output  [31:0] add32_646_out;
output   add32_646_out_ap_vld;
output  [31:0] add28_645_out;
output   add28_645_out_ap_vld;
output  [31:0] add32_544_out;
output   add32_544_out_ap_vld;
output  [31:0] add28_543_out;
output   add28_543_out_ap_vld;
output  [31:0] add32_442_out;
output   add32_442_out_ap_vld;
output  [31:0] add28_441_out;
output   add28_441_out_ap_vld;
output  [31:0] add32_340_out;
output   add32_340_out_ap_vld;
output  [31:0] add28_339_out;
output   add28_339_out_ap_vld;
output  [31:0] add32_238_out;
output   add32_238_out_ap_vld;
output  [31:0] add28_237_out;
output   add28_237_out_ap_vld;
output  [31:0] add32_136_out;
output   add32_136_out_ap_vld;
output  [31:0] add28_135_out;
output   add28_135_out_ap_vld;
output  [31:0] add3234_out;
output   add3234_out_ap_vld;
output  [31:0] add2833_out;
output   add2833_out_ap_vld;
output  [31:0] grp_fu_405_p_din0;
output  [31:0] grp_fu_405_p_din1;
output  [0:0] grp_fu_405_p_opcode;
input  [31:0] grp_fu_405_p_dout0;
output   grp_fu_405_p_ce;
output  [31:0] grp_fu_1040_p_din0;
output  [31:0] grp_fu_1040_p_din1;
output  [1:0] grp_fu_1040_p_opcode;
input  [31:0] grp_fu_1040_p_dout0;
output   grp_fu_1040_p_ce;
output  [31:0] grp_fu_1044_p_din0;
output  [31:0] grp_fu_1044_p_din1;
output  [1:0] grp_fu_1044_p_opcode;
input  [31:0] grp_fu_1044_p_dout0;
output   grp_fu_1044_p_ce;
output  [31:0] grp_fu_1048_p_din0;
output  [31:0] grp_fu_1048_p_din1;
output  [1:0] grp_fu_1048_p_opcode;
input  [31:0] grp_fu_1048_p_dout0;
output   grp_fu_1048_p_ce;
output  [31:0] grp_fu_410_p_din0;
output  [31:0] grp_fu_410_p_din1;
input  [31:0] grp_fu_410_p_dout0;
output   grp_fu_410_p_ce;
output  [31:0] grp_fu_415_p_din0;
output  [31:0] grp_fu_415_p_din1;
input  [31:0] grp_fu_415_p_dout0;
output   grp_fu_415_p_ce;
output  [31:0] grp_fu_1052_p_din0;
output  [31:0] grp_fu_1052_p_din1;
input  [31:0] grp_fu_1052_p_dout0;
output   grp_fu_1052_p_ce;
output  [31:0] grp_fu_1056_p_din0;
output  [31:0] grp_fu_1056_p_din1;
input  [31:0] grp_fu_1056_p_dout0;
output   grp_fu_1056_p_ce;

reg ap_idle;
reg residual_ce0;
reg projected_ce0;
reg projected_ce1;
reg add32_1564_out_ap_vld;
reg add28_1563_out_ap_vld;
reg add32_1462_out_ap_vld;
reg add28_1461_out_ap_vld;
reg add32_1360_out_ap_vld;
reg add28_1359_out_ap_vld;
reg add32_1258_out_ap_vld;
reg add28_1257_out_ap_vld;
reg add32_1156_out_ap_vld;
reg add28_1155_out_ap_vld;
reg add32_1054_out_ap_vld;
reg add28_1053_out_ap_vld;
reg add32_952_out_ap_vld;
reg add28_951_out_ap_vld;
reg add32_850_out_ap_vld;
reg add28_849_out_ap_vld;
reg add32_748_out_ap_vld;
reg add28_747_out_ap_vld;
reg add32_646_out_ap_vld;
reg add28_645_out_ap_vld;
reg add32_544_out_ap_vld;
reg add28_543_out_ap_vld;
reg add32_442_out_ap_vld;
reg add28_441_out_ap_vld;
reg add32_340_out_ap_vld;
reg add28_339_out_ap_vld;
reg add32_238_out_ap_vld;
reg add28_237_out_ap_vld;
reg add32_136_out_ap_vld;
reg add28_135_out_ap_vld;
reg add3234_out_ap_vld;
reg add2833_out_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state8_pp0_stage3_iter1;
wire    ap_block_state12_pp0_stage3_iter2;
wire    ap_block_state16_pp0_stage3_iter3;
wire    ap_block_state20_pp0_stage3_iter4;
wire    ap_block_pp0_stage3_subdone;
reg   [0:0] icmp_ln242_reg_2002;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state9_pp0_stage0_iter2;
wire    ap_block_state13_pp0_stage0_iter3;
wire    ap_block_state17_pp0_stage0_iter4;
wire    ap_block_state21_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln242_fu_820_p2;
reg   [0:0] icmp_ln242_reg_2002_pp0_iter1_reg;
reg   [0:0] icmp_ln242_reg_2002_pp0_iter2_reg;
reg   [0:0] icmp_ln242_reg_2002_pp0_iter3_reg;
reg   [0:0] icmp_ln242_reg_2002_pp0_iter4_reg;
wire   [12:0] add_ln248_fu_836_p2;
reg   [12:0] add_ln248_reg_2006;
wire   [13:0] add_ln248_1_fu_854_p2;
reg   [13:0] add_ln248_1_reg_2011;
wire   [13:0] add_ln248_2_fu_870_p2;
reg   [13:0] add_ln248_2_reg_2016;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state6_pp0_stage1_iter1;
wire    ap_block_state10_pp0_stage1_iter2;
wire    ap_block_state14_pp0_stage1_iter3;
wire    ap_block_state18_pp0_stage1_iter4;
wire    ap_block_state22_pp0_stage1_iter5;
wire    ap_block_pp0_stage1_11001;
wire   [31:0] trunc_ln248_fu_893_p1;
reg   [31:0] trunc_ln248_reg_2036;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state7_pp0_stage2_iter1;
wire    ap_block_state11_pp0_stage2_iter2;
wire    ap_block_state15_pp0_stage2_iter3;
wire    ap_block_state19_pp0_stage2_iter4;
wire    ap_block_pp0_stage2_11001;
wire   [31:0] trunc_ln248_1_fu_897_p1;
reg   [31:0] trunc_ln248_1_reg_2041;
reg   [31:0] tmp_s_reg_2046;
reg   [31:0] tmp_59_reg_2051;
reg   [31:0] tmp_60_reg_2056;
reg   [31:0] tmp_61_reg_2061;
reg   [31:0] tmp_62_reg_2066;
reg   [31:0] tmp_63_reg_2071;
reg   [31:0] tmp_64_reg_2076;
reg   [31:0] tmp_65_reg_2081;
reg   [31:0] tmp_31_reg_2086;
reg   [31:0] tmp_66_reg_2091;
reg   [31:0] tmp_67_reg_2096;
reg   [31:0] tmp_68_reg_2101;
reg   [31:0] tmp_69_reg_2106;
reg   [31:0] tmp_70_reg_2111;
reg   [31:0] tmp_71_reg_2116;
wire   [31:0] trunc_ln248_2_fu_1051_p1;
reg   [31:0] trunc_ln248_2_reg_2121;
reg   [31:0] tmp_72_reg_2126;
reg   [31:0] tmp_73_reg_2131;
reg   [31:0] tmp_74_reg_2136;
reg   [31:0] tmp_75_reg_2141;
reg   [31:0] tmp_76_reg_2146;
reg   [31:0] tmp_77_reg_2151;
reg   [31:0] tmp_78_reg_2156;
reg   [31:0] tmp_79_reg_2161;
reg   [31:0] tmp_80_reg_2166;
reg   [31:0] tmp_81_reg_2171;
reg   [31:0] tmp_82_reg_2176;
reg   [31:0] tmp_83_reg_2181;
reg   [31:0] tmp_84_reg_2186;
reg   [31:0] tmp_85_reg_2191;
wire   [31:0] bitcast_ln248_fu_1195_p1;
wire    ap_block_pp0_stage3_11001;
wire   [31:0] bitcast_ln248_1_fu_1199_p1;
wire   [31:0] bitcast_ln248_2_fu_1203_p1;
wire   [31:0] bitcast_ln248_3_fu_1207_p1;
wire   [31:0] bitcast_ln248_4_fu_1211_p1;
wire   [31:0] bitcast_ln248_5_fu_1215_p1;
wire   [31:0] bitcast_ln248_6_fu_1219_p1;
wire   [31:0] bitcast_ln248_7_fu_1223_p1;
wire   [31:0] bitcast_ln248_8_fu_1227_p1;
wire   [31:0] bitcast_ln248_9_fu_1231_p1;
wire   [31:0] bitcast_ln248_10_fu_1235_p1;
wire   [31:0] bitcast_ln248_11_fu_1239_p1;
wire   [31:0] bitcast_ln248_12_fu_1243_p1;
wire   [31:0] bitcast_ln248_13_fu_1247_p1;
wire   [31:0] bitcast_ln248_14_fu_1251_p1;
wire   [31:0] bitcast_ln248_15_fu_1255_p1;
wire   [31:0] bitcast_ln248_16_fu_1259_p1;
wire   [31:0] bitcast_ln248_17_fu_1263_p1;
wire   [31:0] bitcast_ln248_18_fu_1267_p1;
wire   [31:0] bitcast_ln248_19_fu_1271_p1;
wire   [31:0] bitcast_ln248_20_fu_1275_p1;
wire   [31:0] bitcast_ln248_21_fu_1279_p1;
wire   [31:0] bitcast_ln248_22_fu_1283_p1;
wire   [31:0] bitcast_ln248_23_fu_1287_p1;
wire   [31:0] bitcast_ln248_24_fu_1291_p1;
wire   [31:0] bitcast_ln248_25_fu_1295_p1;
wire   [31:0] bitcast_ln248_26_fu_1299_p1;
wire   [31:0] bitcast_ln248_27_fu_1303_p1;
wire   [31:0] bitcast_ln248_28_fu_1307_p1;
wire   [31:0] bitcast_ln248_29_fu_1311_p1;
wire   [31:0] bitcast_ln248_30_fu_1315_p1;
wire   [31:0] bitcast_ln248_31_fu_1319_p1;
reg   [31:0] x_reg_2356;
reg   [31:0] x_1_reg_2363;
reg   [31:0] x_2_reg_2370;
reg   [31:0] x_3_reg_2377;
reg   [31:0] x_4_reg_2404;
reg   [31:0] x_5_reg_2411;
reg   [31:0] x_6_reg_2418;
reg   [31:0] x_7_reg_2425;
reg   [31:0] x_8_reg_2452;
reg   [31:0] x_9_reg_2459;
reg   [31:0] x_16_reg_2466;
reg   [31:0] x_17_reg_2473;
reg   [31:0] x_18_reg_2500;
reg   [31:0] x_19_reg_2507;
reg   [31:0] x_20_reg_2514;
reg   [31:0] x_21_reg_2521;
reg   [31:0] mul_reg_2548;
reg   [31:0] mul29_1_reg_2553;
reg   [31:0] mul29_2_reg_2558;
reg   [31:0] mul29_3_reg_2563;
reg   [31:0] mul29_4_reg_2588;
reg   [31:0] mul29_5_reg_2593;
reg   [31:0] mul29_6_reg_2598;
reg   [31:0] mul29_7_reg_2603;
reg   [31:0] mul29_8_reg_2628;
reg   [31:0] mul29_9_reg_2633;
reg   [31:0] mul29_s_reg_2638;
reg   [31:0] mul29_10_reg_2643;
reg   [31:0] mul29_11_reg_2668;
reg   [31:0] mul29_12_reg_2673;
reg   [31:0] mul29_13_reg_2678;
reg   [31:0] mul29_14_reg_2683;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage1_subdone;
wire   [63:0] zext_ln248_1_fu_881_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln248_3_fu_885_p1;
wire   [63:0] zext_ln248_5_fu_889_p1;
reg   [31:0] sum_bank_16_fu_182;
wire   [31:0] grp_fu_604_p2;
reg   [31:0] ap_sig_allocacmp_sum_bank_16_load_1;
wire    ap_block_pp0_stage2;
wire    ap_loop_init;
reg   [31:0] square_bank_16_fu_186;
wire   [31:0] grp_fu_620_p2;
reg   [31:0] ap_sig_allocacmp_square_bank_16_load_1;
reg   [31:0] sum_bank_17_fu_190;
wire   [31:0] grp_fu_608_p2;
reg   [31:0] ap_sig_allocacmp_sum_bank_17_load_1;
reg   [31:0] square_bank_17_fu_194;
wire   [31:0] grp_fu_624_p2;
reg   [31:0] ap_sig_allocacmp_square_bank_17_load_1;
reg   [31:0] sum_bank_18_fu_198;
wire   [31:0] grp_fu_612_p2;
reg   [31:0] ap_sig_allocacmp_sum_bank_18_load_1;
reg   [31:0] square_bank_18_fu_202;
wire   [31:0] grp_fu_628_p2;
reg   [31:0] ap_sig_allocacmp_square_bank_18_load_1;
reg   [31:0] sum_bank_19_fu_206;
wire   [31:0] grp_fu_616_p2;
reg   [31:0] ap_sig_allocacmp_sum_bank_19_load_1;
reg   [31:0] square_bank_19_fu_210;
wire   [31:0] grp_fu_632_p2;
reg   [31:0] ap_sig_allocacmp_square_bank_19_load_1;
reg   [31:0] sum_bank_20_fu_214;
reg   [31:0] ap_sig_allocacmp_sum_bank_20_load_1;
wire    ap_block_pp0_stage3;
reg   [31:0] square_bank_20_fu_218;
reg   [31:0] ap_sig_allocacmp_square_bank_20_load_1;
reg   [31:0] sum_bank_21_fu_222;
reg   [31:0] ap_sig_allocacmp_sum_bank_21_load_1;
reg   [31:0] square_bank_21_fu_226;
reg   [31:0] ap_sig_allocacmp_square_bank_21_load_1;
reg   [31:0] sum_bank_22_fu_230;
reg   [31:0] ap_sig_allocacmp_sum_bank_22_load_1;
reg   [31:0] square_bank_22_fu_234;
reg   [31:0] ap_sig_allocacmp_square_bank_22_load_1;
reg   [31:0] sum_bank_23_fu_238;
reg   [31:0] ap_sig_allocacmp_sum_bank_23_load_1;
reg   [31:0] square_bank_23_fu_242;
reg   [31:0] ap_sig_allocacmp_square_bank_23_load_1;
reg   [31:0] sum_bank_24_fu_246;
reg   [31:0] ap_sig_allocacmp_sum_bank_24_load_1;
wire    ap_block_pp0_stage0;
reg   [31:0] square_bank_24_fu_250;
reg   [31:0] ap_sig_allocacmp_square_bank_24_load_1;
reg   [31:0] sum_bank_25_fu_254;
reg   [31:0] ap_sig_allocacmp_sum_bank_25_load_1;
reg   [31:0] square_bank_25_fu_258;
reg   [31:0] ap_sig_allocacmp_square_bank_25_load_1;
reg   [31:0] sum_bank_26_fu_262;
reg   [31:0] ap_sig_allocacmp_sum_bank_26_load_1;
reg   [31:0] square_bank_26_fu_266;
reg   [31:0] ap_sig_allocacmp_square_bank_26_load_1;
reg   [31:0] sum_bank_27_fu_270;
reg   [31:0] ap_sig_allocacmp_sum_bank_27_load_1;
reg   [31:0] square_bank_27_fu_274;
reg   [31:0] ap_sig_allocacmp_square_bank_27_load_1;
reg   [31:0] sum_bank_28_fu_278;
reg   [31:0] ap_sig_allocacmp_sum_bank_28_load_1;
reg   [31:0] square_bank_28_fu_282;
reg   [31:0] ap_sig_allocacmp_square_bank_28_load_1;
reg   [31:0] sum_bank_29_fu_286;
reg   [31:0] ap_sig_allocacmp_sum_bank_29_load_1;
reg   [31:0] square_bank_29_fu_290;
reg   [31:0] ap_sig_allocacmp_square_bank_29_load_1;
reg   [31:0] sum_bank_30_fu_294;
reg   [31:0] ap_sig_allocacmp_sum_bank_30_load_1;
reg   [31:0] square_bank_30_fu_298;
reg   [31:0] ap_sig_allocacmp_square_bank_30_load_1;
reg   [31:0] sum_bank_31_fu_302;
reg   [31:0] ap_sig_allocacmp_sum_bank_31_load_1;
reg   [31:0] square_bank_31_fu_306;
reg   [31:0] ap_sig_allocacmp_square_bank_31_load_1;
reg   [5:0] p_fu_310;
wire   [5:0] add_ln242_fu_826_p2;
reg   [5:0] ap_sig_allocacmp_p_2;
wire    ap_block_pp0_stage1_01001;
reg   [31:0] grp_fu_588_p0;
reg   [31:0] grp_fu_588_p1;
reg   [31:0] grp_fu_592_p0;
reg   [31:0] grp_fu_592_p1;
reg   [31:0] grp_fu_596_p0;
reg   [31:0] grp_fu_596_p1;
reg   [31:0] grp_fu_600_p0;
reg   [31:0] grp_fu_600_p1;
reg   [31:0] grp_fu_604_p0;
reg   [31:0] grp_fu_604_p1;
reg   [31:0] grp_fu_608_p0;
reg   [31:0] grp_fu_608_p1;
reg   [31:0] grp_fu_612_p0;
reg   [31:0] grp_fu_612_p1;
reg   [31:0] grp_fu_616_p0;
reg   [31:0] grp_fu_616_p1;
reg   [31:0] grp_fu_620_p0;
reg   [31:0] grp_fu_620_p1;
reg   [31:0] grp_fu_624_p0;
reg   [31:0] grp_fu_624_p1;
reg   [31:0] grp_fu_628_p0;
reg   [31:0] grp_fu_628_p1;
reg   [31:0] grp_fu_632_p0;
reg   [31:0] grp_fu_632_p1;
reg   [31:0] grp_fu_636_p0;
reg   [31:0] grp_fu_636_p1;
reg   [31:0] grp_fu_640_p0;
reg   [31:0] grp_fu_640_p1;
reg   [31:0] grp_fu_644_p0;
reg   [31:0] grp_fu_644_p1;
reg   [31:0] grp_fu_648_p0;
reg   [31:0] grp_fu_648_p1;
wire   [12:0] zext_ln248_fu_832_p1;
wire   [6:0] shl_ln_fu_842_p3;
wire   [13:0] zext_ln248_2_fu_850_p1;
wire   [6:0] or_ln248_fu_860_p2;
wire   [13:0] zext_ln248_4_fu_866_p1;
wire    ap_block_pp0_stage3_00001;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp0_stage1_00001;
wire    ap_block_pp0_stage2_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter4_stage1;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to5;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

bert_attn_out_norm_residual_kernel_fadd_32ns_32ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_no_dsp_1_U564(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_604_p0),
    .din1(grp_fu_604_p1),
    .ce(1'b1),
    .dout(grp_fu_604_p2)
);

bert_attn_out_norm_residual_kernel_fadd_32ns_32ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_no_dsp_1_U565(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_608_p0),
    .din1(grp_fu_608_p1),
    .ce(1'b1),
    .dout(grp_fu_608_p2)
);

bert_attn_out_norm_residual_kernel_fadd_32ns_32ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_no_dsp_1_U566(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_612_p0),
    .din1(grp_fu_612_p1),
    .ce(1'b1),
    .dout(grp_fu_612_p2)
);

bert_attn_out_norm_residual_kernel_fadd_32ns_32ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_no_dsp_1_U567(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_616_p0),
    .din1(grp_fu_616_p1),
    .ce(1'b1),
    .dout(grp_fu_616_p2)
);

bert_attn_out_norm_residual_kernel_fadd_32ns_32ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_no_dsp_1_U568(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_620_p0),
    .din1(grp_fu_620_p1),
    .ce(1'b1),
    .dout(grp_fu_620_p2)
);

bert_attn_out_norm_residual_kernel_fadd_32ns_32ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_no_dsp_1_U569(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_624_p0),
    .din1(grp_fu_624_p1),
    .ce(1'b1),
    .dout(grp_fu_624_p2)
);

bert_attn_out_norm_residual_kernel_fadd_32ns_32ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_no_dsp_1_U570(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_628_p0),
    .din1(grp_fu_628_p1),
    .ce(1'b1),
    .dout(grp_fu_628_p2)
);

bert_attn_out_norm_residual_kernel_fadd_32ns_32ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_no_dsp_1_U571(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_632_p0),
    .din1(grp_fu_632_p1),
    .ce(1'b1),
    .dout(grp_fu_632_p2)
);

bert_attn_out_norm_residual_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter4_stage1) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter4_stage1) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter4_stage1) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter4_stage1) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln242_fu_820_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            p_fu_310 <= add_ln242_fu_826_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            p_fu_310 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        square_bank_16_fu_186 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        square_bank_16_fu_186 <= grp_fu_620_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        square_bank_17_fu_194 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        square_bank_17_fu_194 <= grp_fu_624_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        square_bank_18_fu_202 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        square_bank_18_fu_202 <= grp_fu_628_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        square_bank_19_fu_210 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        square_bank_19_fu_210 <= grp_fu_632_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        square_bank_20_fu_218 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        square_bank_20_fu_218 <= grp_fu_620_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        square_bank_21_fu_226 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        square_bank_21_fu_226 <= grp_fu_624_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        square_bank_22_fu_234 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        square_bank_22_fu_234 <= grp_fu_628_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        square_bank_23_fu_242 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        square_bank_23_fu_242 <= grp_fu_632_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            square_bank_24_fu_250 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            square_bank_24_fu_250 <= grp_fu_620_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            square_bank_25_fu_258 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            square_bank_25_fu_258 <= grp_fu_624_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            square_bank_26_fu_266 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            square_bank_26_fu_266 <= grp_fu_628_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            square_bank_27_fu_274 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            square_bank_27_fu_274 <= grp_fu_632_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        square_bank_28_fu_282 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        square_bank_28_fu_282 <= grp_fu_620_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        square_bank_29_fu_290 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        square_bank_29_fu_290 <= grp_fu_624_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        square_bank_30_fu_298 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        square_bank_30_fu_298 <= grp_fu_628_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        square_bank_31_fu_306 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        square_bank_31_fu_306 <= grp_fu_632_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_bank_16_fu_182 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sum_bank_16_fu_182 <= grp_fu_604_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_bank_17_fu_190 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sum_bank_17_fu_190 <= grp_fu_608_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_bank_18_fu_198 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sum_bank_18_fu_198 <= grp_fu_612_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_bank_19_fu_206 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sum_bank_19_fu_206 <= grp_fu_616_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_bank_20_fu_214 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        sum_bank_20_fu_214 <= grp_fu_604_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_bank_21_fu_222 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        sum_bank_21_fu_222 <= grp_fu_608_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_bank_22_fu_230 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        sum_bank_22_fu_230 <= grp_fu_612_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_bank_23_fu_238 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        sum_bank_23_fu_238 <= grp_fu_616_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            sum_bank_24_fu_246 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            sum_bank_24_fu_246 <= grp_fu_604_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            sum_bank_25_fu_254 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            sum_bank_25_fu_254 <= grp_fu_608_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            sum_bank_26_fu_262 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            sum_bank_26_fu_262 <= grp_fu_612_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            sum_bank_27_fu_270 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            sum_bank_27_fu_270 <= grp_fu_616_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_bank_28_fu_278 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sum_bank_28_fu_278 <= grp_fu_604_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_bank_29_fu_286 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sum_bank_29_fu_286 <= grp_fu_608_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_bank_30_fu_294 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sum_bank_30_fu_294 <= grp_fu_612_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_bank_31_fu_302 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sum_bank_31_fu_302 <= grp_fu_616_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln242_fu_820_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln248_1_reg_2011 <= add_ln248_1_fu_854_p2;
        add_ln248_2_reg_2016 <= add_ln248_2_fu_870_p2;
        add_ln248_reg_2006 <= add_ln248_fu_836_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln242_reg_2002 <= icmp_ln242_fu_820_p2;
        icmp_ln242_reg_2002_pp0_iter1_reg <= icmp_ln242_reg_2002;
        icmp_ln242_reg_2002_pp0_iter2_reg <= icmp_ln242_reg_2002_pp0_iter1_reg;
        icmp_ln242_reg_2002_pp0_iter3_reg <= icmp_ln242_reg_2002_pp0_iter2_reg;
        icmp_ln242_reg_2002_pp0_iter4_reg <= icmp_ln242_reg_2002_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul29_10_reg_2643 <= grp_fu_1056_p_dout0;
        mul29_8_reg_2628 <= grp_fu_410_p_dout0;
        mul29_9_reg_2633 <= grp_fu_415_p_dout0;
        mul29_s_reg_2638 <= grp_fu_1052_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul29_11_reg_2668 <= grp_fu_410_p_dout0;
        mul29_12_reg_2673 <= grp_fu_415_p_dout0;
        mul29_13_reg_2678 <= grp_fu_1052_p_dout0;
        mul29_14_reg_2683 <= grp_fu_1056_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul29_1_reg_2553 <= grp_fu_415_p_dout0;
        mul29_2_reg_2558 <= grp_fu_1052_p_dout0;
        mul29_3_reg_2563 <= grp_fu_1056_p_dout0;
        mul_reg_2548 <= grp_fu_410_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul29_4_reg_2588 <= grp_fu_410_p_dout0;
        mul29_5_reg_2593 <= grp_fu_415_p_dout0;
        mul29_6_reg_2598 <= grp_fu_1052_p_dout0;
        mul29_7_reg_2603 <= grp_fu_1056_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln242_reg_2002 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_31_reg_2086 <= {{residual_q0[191:160]}};
        tmp_59_reg_2051 <= {{projected_q1[63:32]}};
        tmp_60_reg_2056 <= {{residual_q0[95:64]}};
        tmp_61_reg_2061 <= {{projected_q1[95:64]}};
        tmp_62_reg_2066 <= {{residual_q0[127:96]}};
        tmp_63_reg_2071 <= {{projected_q1[127:96]}};
        tmp_64_reg_2076 <= {{residual_q0[159:128]}};
        tmp_65_reg_2081 <= {{projected_q1[159:128]}};
        tmp_66_reg_2091 <= {{projected_q1[191:160]}};
        tmp_67_reg_2096 <= {{residual_q0[223:192]}};
        tmp_68_reg_2101 <= {{projected_q1[223:192]}};
        tmp_69_reg_2106 <= {{residual_q0[255:224]}};
        tmp_70_reg_2111 <= {{projected_q1[255:224]}};
        tmp_71_reg_2116 <= {{residual_q0[287:256]}};
        tmp_72_reg_2126 <= {{residual_q0[319:288]}};
        tmp_73_reg_2131 <= {{projected_q0[63:32]}};
        tmp_74_reg_2136 <= {{residual_q0[351:320]}};
        tmp_75_reg_2141 <= {{projected_q0[95:64]}};
        tmp_76_reg_2146 <= {{residual_q0[383:352]}};
        tmp_77_reg_2151 <= {{projected_q0[127:96]}};
        tmp_78_reg_2156 <= {{residual_q0[415:384]}};
        tmp_79_reg_2161 <= {{projected_q0[159:128]}};
        tmp_80_reg_2166 <= {{residual_q0[447:416]}};
        tmp_81_reg_2171 <= {{projected_q0[191:160]}};
        tmp_82_reg_2176 <= {{residual_q0[479:448]}};
        tmp_83_reg_2181 <= {{projected_q0[223:192]}};
        tmp_84_reg_2186 <= {{residual_q0[511:480]}};
        tmp_85_reg_2191 <= {{projected_q0[255:224]}};
        tmp_s_reg_2046 <= {{residual_q0[63:32]}};
        trunc_ln248_1_reg_2041 <= trunc_ln248_1_fu_897_p1;
        trunc_ln248_2_reg_2121 <= trunc_ln248_2_fu_1051_p1;
        trunc_ln248_reg_2036 <= trunc_ln248_fu_893_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        x_16_reg_2466 <= grp_fu_1044_p_dout0;
        x_17_reg_2473 <= grp_fu_1048_p_dout0;
        x_8_reg_2452 <= grp_fu_405_p_dout0;
        x_9_reg_2459 <= grp_fu_1040_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_18_reg_2500 <= grp_fu_405_p_dout0;
        x_19_reg_2507 <= grp_fu_1040_p_dout0;
        x_20_reg_2514 <= grp_fu_1044_p_dout0;
        x_21_reg_2521 <= grp_fu_1048_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        x_1_reg_2363 <= grp_fu_1040_p_dout0;
        x_2_reg_2370 <= grp_fu_1044_p_dout0;
        x_3_reg_2377 <= grp_fu_1048_p_dout0;
        x_reg_2356 <= grp_fu_405_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        x_4_reg_2404 <= grp_fu_405_p_dout0;
        x_5_reg_2411 <= grp_fu_1040_p_dout0;
        x_6_reg_2418 <= grp_fu_1044_p_dout0;
        x_7_reg_2425 <= grp_fu_1048_p_dout0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add2833_out_ap_vld = 1'b1;
    end else begin
        add2833_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_1053_out_ap_vld = 1'b1;
    end else begin
        add28_1053_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_1155_out_ap_vld = 1'b1;
    end else begin
        add28_1155_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_1257_out_ap_vld = 1'b1;
    end else begin
        add28_1257_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_1359_out_ap_vld = 1'b1;
    end else begin
        add28_1359_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_135_out_ap_vld = 1'b1;
    end else begin
        add28_135_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_1461_out_ap_vld = 1'b1;
    end else begin
        add28_1461_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_1563_out_ap_vld = 1'b1;
    end else begin
        add28_1563_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_237_out_ap_vld = 1'b1;
    end else begin
        add28_237_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_339_out_ap_vld = 1'b1;
    end else begin
        add28_339_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_441_out_ap_vld = 1'b1;
    end else begin
        add28_441_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_543_out_ap_vld = 1'b1;
    end else begin
        add28_543_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_645_out_ap_vld = 1'b1;
    end else begin
        add28_645_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_747_out_ap_vld = 1'b1;
    end else begin
        add28_747_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_849_out_ap_vld = 1'b1;
    end else begin
        add28_849_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_951_out_ap_vld = 1'b1;
    end else begin
        add28_951_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add3234_out_ap_vld = 1'b1;
    end else begin
        add3234_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_1054_out_ap_vld = 1'b1;
    end else begin
        add32_1054_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_1156_out_ap_vld = 1'b1;
    end else begin
        add32_1156_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_1258_out_ap_vld = 1'b1;
    end else begin
        add32_1258_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_1360_out_ap_vld = 1'b1;
    end else begin
        add32_1360_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_136_out_ap_vld = 1'b1;
    end else begin
        add32_136_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_1462_out_ap_vld = 1'b1;
    end else begin
        add32_1462_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_1564_out_ap_vld = 1'b1;
    end else begin
        add32_1564_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_238_out_ap_vld = 1'b1;
    end else begin
        add32_238_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_340_out_ap_vld = 1'b1;
    end else begin
        add32_340_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_442_out_ap_vld = 1'b1;
    end else begin
        add32_442_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_544_out_ap_vld = 1'b1;
    end else begin
        add32_544_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_646_out_ap_vld = 1'b1;
    end else begin
        add32_646_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_748_out_ap_vld = 1'b1;
    end else begin
        add32_748_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_850_out_ap_vld = 1'b1;
    end else begin
        add32_850_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add32_952_out_ap_vld = 1'b1;
    end else begin
        add32_952_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln242_reg_2002 == 1'd1) & (1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln242_reg_2002_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_p_2 = 6'd0;
    end else begin
        ap_sig_allocacmp_p_2 = p_fu_310;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_square_bank_16_load_1 = grp_fu_620_p2;
    end else begin
        ap_sig_allocacmp_square_bank_16_load_1 = square_bank_16_fu_186;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_square_bank_17_load_1 = grp_fu_624_p2;
    end else begin
        ap_sig_allocacmp_square_bank_17_load_1 = square_bank_17_fu_194;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_square_bank_18_load_1 = grp_fu_628_p2;
    end else begin
        ap_sig_allocacmp_square_bank_18_load_1 = square_bank_18_fu_202;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_square_bank_19_load_1 = grp_fu_632_p2;
    end else begin
        ap_sig_allocacmp_square_bank_19_load_1 = square_bank_19_fu_210;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_square_bank_20_load_1 = grp_fu_620_p2;
    end else begin
        ap_sig_allocacmp_square_bank_20_load_1 = square_bank_20_fu_218;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_square_bank_21_load_1 = grp_fu_624_p2;
    end else begin
        ap_sig_allocacmp_square_bank_21_load_1 = square_bank_21_fu_226;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_square_bank_22_load_1 = grp_fu_628_p2;
    end else begin
        ap_sig_allocacmp_square_bank_22_load_1 = square_bank_22_fu_234;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_square_bank_23_load_1 = grp_fu_632_p2;
    end else begin
        ap_sig_allocacmp_square_bank_23_load_1 = square_bank_23_fu_242;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_square_bank_24_load_1 = grp_fu_620_p2;
    end else begin
        ap_sig_allocacmp_square_bank_24_load_1 = square_bank_24_fu_250;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_square_bank_25_load_1 = grp_fu_624_p2;
    end else begin
        ap_sig_allocacmp_square_bank_25_load_1 = square_bank_25_fu_258;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_square_bank_26_load_1 = grp_fu_628_p2;
    end else begin
        ap_sig_allocacmp_square_bank_26_load_1 = square_bank_26_fu_266;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_square_bank_27_load_1 = grp_fu_632_p2;
    end else begin
        ap_sig_allocacmp_square_bank_27_load_1 = square_bank_27_fu_274;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_square_bank_28_load_1 = grp_fu_620_p2;
    end else begin
        ap_sig_allocacmp_square_bank_28_load_1 = square_bank_28_fu_282;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_square_bank_29_load_1 = grp_fu_624_p2;
    end else begin
        ap_sig_allocacmp_square_bank_29_load_1 = square_bank_29_fu_290;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_square_bank_30_load_1 = grp_fu_628_p2;
    end else begin
        ap_sig_allocacmp_square_bank_30_load_1 = square_bank_30_fu_298;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_square_bank_31_load_1 = grp_fu_632_p2;
    end else begin
        ap_sig_allocacmp_square_bank_31_load_1 = square_bank_31_fu_306;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_sum_bank_16_load_1 = grp_fu_604_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_16_load_1 = sum_bank_16_fu_182;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_sum_bank_17_load_1 = grp_fu_608_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_17_load_1 = sum_bank_17_fu_190;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_sum_bank_18_load_1 = grp_fu_612_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_18_load_1 = sum_bank_18_fu_198;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_sum_bank_19_load_1 = grp_fu_616_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_19_load_1 = sum_bank_19_fu_206;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_sum_bank_20_load_1 = grp_fu_604_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_20_load_1 = sum_bank_20_fu_214;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_sum_bank_21_load_1 = grp_fu_608_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_21_load_1 = sum_bank_21_fu_222;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_sum_bank_22_load_1 = grp_fu_612_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_22_load_1 = sum_bank_22_fu_230;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_sum_bank_23_load_1 = grp_fu_616_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_23_load_1 = sum_bank_23_fu_238;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_sum_bank_24_load_1 = grp_fu_604_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_24_load_1 = sum_bank_24_fu_246;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_sum_bank_25_load_1 = grp_fu_608_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_25_load_1 = sum_bank_25_fu_254;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_sum_bank_26_load_1 = grp_fu_612_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_26_load_1 = sum_bank_26_fu_262;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_sum_bank_27_load_1 = grp_fu_616_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_27_load_1 = sum_bank_27_fu_270;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_sum_bank_28_load_1 = grp_fu_604_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_28_load_1 = sum_bank_28_fu_278;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_sum_bank_29_load_1 = grp_fu_608_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_29_load_1 = sum_bank_29_fu_286;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_sum_bank_30_load_1 = grp_fu_612_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_30_load_1 = sum_bank_30_fu_294;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_sum_bank_31_load_1 = grp_fu_616_p2;
    end else begin
        ap_sig_allocacmp_sum_bank_31_load_1 = sum_bank_31_fu_302;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_588_p0 = bitcast_ln248_24_fu_1291_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_588_p0 = bitcast_ln248_16_fu_1259_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_588_p0 = bitcast_ln248_8_fu_1227_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_588_p0 = bitcast_ln248_fu_1195_p1;
    end else begin
        grp_fu_588_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_588_p1 = bitcast_ln248_25_fu_1295_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_588_p1 = bitcast_ln248_17_fu_1263_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_588_p1 = bitcast_ln248_9_fu_1231_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_588_p1 = bitcast_ln248_1_fu_1199_p1;
    end else begin
        grp_fu_588_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_592_p0 = bitcast_ln248_26_fu_1299_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_592_p0 = bitcast_ln248_18_fu_1267_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_592_p0 = bitcast_ln248_10_fu_1235_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_592_p0 = bitcast_ln248_2_fu_1203_p1;
    end else begin
        grp_fu_592_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_592_p1 = bitcast_ln248_27_fu_1303_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_592_p1 = bitcast_ln248_19_fu_1271_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_592_p1 = bitcast_ln248_11_fu_1239_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_592_p1 = bitcast_ln248_3_fu_1207_p1;
    end else begin
        grp_fu_592_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_596_p0 = bitcast_ln248_28_fu_1307_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_596_p0 = bitcast_ln248_20_fu_1275_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_596_p0 = bitcast_ln248_12_fu_1243_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_596_p0 = bitcast_ln248_4_fu_1211_p1;
    end else begin
        grp_fu_596_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_596_p1 = bitcast_ln248_29_fu_1311_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_596_p1 = bitcast_ln248_21_fu_1279_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_596_p1 = bitcast_ln248_13_fu_1247_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_596_p1 = bitcast_ln248_5_fu_1215_p1;
    end else begin
        grp_fu_596_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_600_p0 = bitcast_ln248_30_fu_1315_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_600_p0 = bitcast_ln248_22_fu_1283_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_600_p0 = bitcast_ln248_14_fu_1251_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_600_p0 = bitcast_ln248_6_fu_1219_p1;
    end else begin
        grp_fu_600_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_600_p1 = bitcast_ln248_31_fu_1319_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_600_p1 = bitcast_ln248_23_fu_1287_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_600_p1 = bitcast_ln248_15_fu_1255_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_600_p1 = bitcast_ln248_7_fu_1223_p1;
    end else begin
        grp_fu_600_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_604_p0 = ap_sig_allocacmp_sum_bank_28_load_1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_604_p0 = ap_sig_allocacmp_sum_bank_24_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_604_p0 = ap_sig_allocacmp_sum_bank_20_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_604_p0 = ap_sig_allocacmp_sum_bank_16_load_1;
    end else begin
        grp_fu_604_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_604_p1 = x_18_reg_2500;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_604_p1 = x_8_reg_2452;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_604_p1 = x_4_reg_2404;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_604_p1 = x_reg_2356;
    end else begin
        grp_fu_604_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_608_p0 = ap_sig_allocacmp_sum_bank_29_load_1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_608_p0 = ap_sig_allocacmp_sum_bank_25_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_608_p0 = ap_sig_allocacmp_sum_bank_21_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_608_p0 = ap_sig_allocacmp_sum_bank_17_load_1;
    end else begin
        grp_fu_608_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_608_p1 = x_19_reg_2507;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_608_p1 = x_9_reg_2459;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_608_p1 = x_5_reg_2411;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_608_p1 = x_1_reg_2363;
    end else begin
        grp_fu_608_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_612_p0 = ap_sig_allocacmp_sum_bank_30_load_1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_612_p0 = ap_sig_allocacmp_sum_bank_26_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_612_p0 = ap_sig_allocacmp_sum_bank_22_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_612_p0 = ap_sig_allocacmp_sum_bank_18_load_1;
    end else begin
        grp_fu_612_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_612_p1 = x_20_reg_2514;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_612_p1 = x_16_reg_2466;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_612_p1 = x_6_reg_2418;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_612_p1 = x_2_reg_2370;
    end else begin
        grp_fu_612_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_616_p0 = ap_sig_allocacmp_sum_bank_31_load_1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_616_p0 = ap_sig_allocacmp_sum_bank_27_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_616_p0 = ap_sig_allocacmp_sum_bank_23_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_616_p0 = ap_sig_allocacmp_sum_bank_19_load_1;
    end else begin
        grp_fu_616_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_616_p1 = x_21_reg_2521;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_616_p1 = x_17_reg_2473;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_616_p1 = x_7_reg_2425;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_616_p1 = x_3_reg_2377;
    end else begin
        grp_fu_616_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_620_p0 = ap_sig_allocacmp_square_bank_28_load_1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_620_p0 = ap_sig_allocacmp_square_bank_24_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_620_p0 = ap_sig_allocacmp_square_bank_20_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_620_p0 = ap_sig_allocacmp_square_bank_16_load_1;
    end else begin
        grp_fu_620_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_620_p1 = mul29_11_reg_2668;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_620_p1 = mul29_8_reg_2628;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_620_p1 = mul29_4_reg_2588;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_620_p1 = mul_reg_2548;
    end else begin
        grp_fu_620_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_624_p0 = ap_sig_allocacmp_square_bank_29_load_1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_624_p0 = ap_sig_allocacmp_square_bank_25_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_624_p0 = ap_sig_allocacmp_square_bank_21_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_624_p0 = ap_sig_allocacmp_square_bank_17_load_1;
    end else begin
        grp_fu_624_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_624_p1 = mul29_12_reg_2673;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_624_p1 = mul29_9_reg_2633;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_624_p1 = mul29_5_reg_2593;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_624_p1 = mul29_1_reg_2553;
    end else begin
        grp_fu_624_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_628_p0 = ap_sig_allocacmp_square_bank_30_load_1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_628_p0 = ap_sig_allocacmp_square_bank_26_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_628_p0 = ap_sig_allocacmp_square_bank_22_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_628_p0 = ap_sig_allocacmp_square_bank_18_load_1;
    end else begin
        grp_fu_628_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_628_p1 = mul29_13_reg_2678;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_628_p1 = mul29_s_reg_2638;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_628_p1 = mul29_6_reg_2598;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_628_p1 = mul29_2_reg_2558;
    end else begin
        grp_fu_628_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_632_p0 = ap_sig_allocacmp_square_bank_31_load_1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_632_p0 = ap_sig_allocacmp_square_bank_27_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_632_p0 = ap_sig_allocacmp_square_bank_23_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_632_p0 = ap_sig_allocacmp_square_bank_19_load_1;
    end else begin
        grp_fu_632_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_632_p1 = mul29_14_reg_2683;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_632_p1 = mul29_10_reg_2643;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_632_p1 = mul29_7_reg_2603;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_632_p1 = mul29_3_reg_2563;
    end else begin
        grp_fu_632_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_636_p0 = x_18_reg_2500;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_636_p0 = x_8_reg_2452;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_636_p0 = x_4_reg_2404;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_636_p0 = x_reg_2356;
    end else begin
        grp_fu_636_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_636_p1 = x_18_reg_2500;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_636_p1 = x_8_reg_2452;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_636_p1 = x_4_reg_2404;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_636_p1 = x_reg_2356;
    end else begin
        grp_fu_636_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_640_p0 = x_19_reg_2507;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_640_p0 = x_9_reg_2459;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_640_p0 = x_5_reg_2411;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_640_p0 = x_1_reg_2363;
    end else begin
        grp_fu_640_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_640_p1 = x_19_reg_2507;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_640_p1 = x_9_reg_2459;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_640_p1 = x_5_reg_2411;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_640_p1 = x_1_reg_2363;
    end else begin
        grp_fu_640_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_644_p0 = x_20_reg_2514;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_644_p0 = x_16_reg_2466;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_644_p0 = x_6_reg_2418;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_644_p0 = x_2_reg_2370;
    end else begin
        grp_fu_644_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_644_p1 = x_20_reg_2514;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_644_p1 = x_16_reg_2466;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_644_p1 = x_6_reg_2418;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_644_p1 = x_2_reg_2370;
    end else begin
        grp_fu_644_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_648_p0 = x_21_reg_2521;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_648_p0 = x_17_reg_2473;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_648_p0 = x_7_reg_2425;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_648_p0 = x_3_reg_2377;
    end else begin
        grp_fu_648_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_648_p1 = x_21_reg_2521;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_648_p1 = x_17_reg_2473;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_648_p1 = x_7_reg_2425;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_648_p1 = x_3_reg_2377;
    end else begin
        grp_fu_648_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        projected_ce0 = 1'b1;
    end else begin
        projected_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        projected_ce1 = 1'b1;
    end else begin
        projected_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        residual_ce0 = 1'b1;
    end else begin
        residual_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter4_stage1) & (ap_idle_pp0_0to3 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add2833_out = sum_bank_16_fu_182;

assign add28_1053_out = sum_bank_26_fu_262;

assign add28_1155_out = sum_bank_27_fu_270;

assign add28_1257_out = sum_bank_28_fu_278;

assign add28_1359_out = sum_bank_29_fu_286;

assign add28_135_out = sum_bank_17_fu_190;

assign add28_1461_out = sum_bank_30_fu_294;

assign add28_1563_out = sum_bank_31_fu_302;

assign add28_237_out = sum_bank_18_fu_198;

assign add28_339_out = sum_bank_19_fu_206;

assign add28_441_out = sum_bank_20_fu_214;

assign add28_543_out = sum_bank_21_fu_222;

assign add28_645_out = sum_bank_22_fu_230;

assign add28_747_out = sum_bank_23_fu_238;

assign add28_849_out = sum_bank_24_fu_246;

assign add28_951_out = sum_bank_25_fu_254;

assign add3234_out = square_bank_16_fu_186;

assign add32_1054_out = square_bank_26_fu_266;

assign add32_1156_out = square_bank_27_fu_274;

assign add32_1258_out = square_bank_28_fu_282;

assign add32_1360_out = square_bank_29_fu_290;

assign add32_136_out = square_bank_17_fu_194;

assign add32_1462_out = square_bank_30_fu_298;

assign add32_1564_out = square_bank_31_fu_306;

assign add32_238_out = square_bank_18_fu_202;

assign add32_340_out = square_bank_19_fu_210;

assign add32_442_out = square_bank_20_fu_218;

assign add32_544_out = square_bank_21_fu_226;

assign add32_646_out = square_bank_22_fu_234;

assign add32_748_out = square_bank_23_fu_242;

assign add32_850_out = square_bank_24_fu_250;

assign add32_952_out = square_bank_25_fu_258;

assign add_ln242_fu_826_p2 = (ap_sig_allocacmp_p_2 + 6'd1);

assign add_ln248_1_fu_854_p2 = (sub_ln248_1 + zext_ln248_2_fu_850_p1);

assign add_ln248_2_fu_870_p2 = (sub_ln248_1 + zext_ln248_4_fu_866_p1);

assign add_ln248_fu_836_p2 = (sub_ln248 + zext_ln248_fu_832_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign bitcast_ln248_10_fu_1235_p1 = tmp_31_reg_2086;

assign bitcast_ln248_11_fu_1239_p1 = tmp_66_reg_2091;

assign bitcast_ln248_12_fu_1243_p1 = tmp_67_reg_2096;

assign bitcast_ln248_13_fu_1247_p1 = tmp_68_reg_2101;

assign bitcast_ln248_14_fu_1251_p1 = tmp_69_reg_2106;

assign bitcast_ln248_15_fu_1255_p1 = tmp_70_reg_2111;

assign bitcast_ln248_16_fu_1259_p1 = tmp_71_reg_2116;

assign bitcast_ln248_17_fu_1263_p1 = trunc_ln248_2_reg_2121;

assign bitcast_ln248_18_fu_1267_p1 = tmp_72_reg_2126;

assign bitcast_ln248_19_fu_1271_p1 = tmp_73_reg_2131;

assign bitcast_ln248_1_fu_1199_p1 = trunc_ln248_1_reg_2041;

assign bitcast_ln248_20_fu_1275_p1 = tmp_74_reg_2136;

assign bitcast_ln248_21_fu_1279_p1 = tmp_75_reg_2141;

assign bitcast_ln248_22_fu_1283_p1 = tmp_76_reg_2146;

assign bitcast_ln248_23_fu_1287_p1 = tmp_77_reg_2151;

assign bitcast_ln248_24_fu_1291_p1 = tmp_78_reg_2156;

assign bitcast_ln248_25_fu_1295_p1 = tmp_79_reg_2161;

assign bitcast_ln248_26_fu_1299_p1 = tmp_80_reg_2166;

assign bitcast_ln248_27_fu_1303_p1 = tmp_81_reg_2171;

assign bitcast_ln248_28_fu_1307_p1 = tmp_82_reg_2176;

assign bitcast_ln248_29_fu_1311_p1 = tmp_83_reg_2181;

assign bitcast_ln248_2_fu_1203_p1 = tmp_s_reg_2046;

assign bitcast_ln248_30_fu_1315_p1 = tmp_84_reg_2186;

assign bitcast_ln248_31_fu_1319_p1 = tmp_85_reg_2191;

assign bitcast_ln248_3_fu_1207_p1 = tmp_59_reg_2051;

assign bitcast_ln248_4_fu_1211_p1 = tmp_60_reg_2056;

assign bitcast_ln248_5_fu_1215_p1 = tmp_61_reg_2061;

assign bitcast_ln248_6_fu_1219_p1 = tmp_62_reg_2066;

assign bitcast_ln248_7_fu_1223_p1 = tmp_63_reg_2071;

assign bitcast_ln248_8_fu_1227_p1 = tmp_64_reg_2076;

assign bitcast_ln248_9_fu_1231_p1 = tmp_65_reg_2081;

assign bitcast_ln248_fu_1195_p1 = trunc_ln248_reg_2036;

assign grp_fu_1040_p_ce = 1'b1;

assign grp_fu_1040_p_din0 = grp_fu_592_p0;

assign grp_fu_1040_p_din1 = grp_fu_592_p1;

assign grp_fu_1040_p_opcode = 2'd0;

assign grp_fu_1044_p_ce = 1'b1;

assign grp_fu_1044_p_din0 = grp_fu_596_p0;

assign grp_fu_1044_p_din1 = grp_fu_596_p1;

assign grp_fu_1044_p_opcode = 2'd0;

assign grp_fu_1048_p_ce = 1'b1;

assign grp_fu_1048_p_din0 = grp_fu_600_p0;

assign grp_fu_1048_p_din1 = grp_fu_600_p1;

assign grp_fu_1048_p_opcode = 2'd0;

assign grp_fu_1052_p_ce = 1'b1;

assign grp_fu_1052_p_din0 = grp_fu_644_p0;

assign grp_fu_1052_p_din1 = grp_fu_644_p1;

assign grp_fu_1056_p_ce = 1'b1;

assign grp_fu_1056_p_din0 = grp_fu_648_p0;

assign grp_fu_1056_p_din1 = grp_fu_648_p1;

assign grp_fu_405_p_ce = 1'b1;

assign grp_fu_405_p_din0 = grp_fu_588_p0;

assign grp_fu_405_p_din1 = grp_fu_588_p1;

assign grp_fu_405_p_opcode = 2'd0;

assign grp_fu_410_p_ce = 1'b1;

assign grp_fu_410_p_din0 = grp_fu_636_p0;

assign grp_fu_410_p_din1 = grp_fu_636_p1;

assign grp_fu_415_p_ce = 1'b1;

assign grp_fu_415_p_din0 = grp_fu_640_p0;

assign grp_fu_415_p_din1 = grp_fu_640_p1;

assign icmp_ln242_fu_820_p2 = ((ap_sig_allocacmp_p_2 == 6'd48) ? 1'b1 : 1'b0);

assign or_ln248_fu_860_p2 = (shl_ln_fu_842_p3 | 7'd1);

assign projected_address0 = zext_ln248_5_fu_889_p1;

assign projected_address1 = zext_ln248_3_fu_885_p1;

assign residual_address0 = zext_ln248_1_fu_881_p1;

assign shl_ln_fu_842_p3 = {{ap_sig_allocacmp_p_2}, {1'd0}};

assign trunc_ln248_1_fu_897_p1 = projected_q1[31:0];

assign trunc_ln248_2_fu_1051_p1 = projected_q0[31:0];

assign trunc_ln248_fu_893_p1 = residual_q0[31:0];

assign zext_ln248_1_fu_881_p1 = add_ln248_reg_2006;

assign zext_ln248_2_fu_850_p1 = shl_ln_fu_842_p3;

assign zext_ln248_3_fu_885_p1 = add_ln248_1_reg_2011;

assign zext_ln248_4_fu_866_p1 = or_ln248_fu_860_p2;

assign zext_ln248_5_fu_889_p1 = add_ln248_2_reg_2016;

assign zext_ln248_fu_832_p1 = ap_sig_allocacmp_p_2;

endmodule //bert_attn_out_norm_residual_kernel_residual_norm_and_write_Pipeline_NORM_REDUCE_PACK
